### ISSUE TITLE
Notify customer to update/install VMware vm tools

### ISSUE THREAD

**Issue by richardtief** [sapcc/elektra#1016]
Hello Team,

we would like to notify the customer on how and if they should install or update the installed VMware VM tools of their resources. This can be for several reasons, such as vulnerability and/or enhanced features and is based on recommendations suggested by VMware.

The following conditions should be met:

1. guest_tools_version < **11.3.5** --> Link how to update
2. guest_tools_version == **0** --> Link how to install
3. All other: Tools up to date  

#### Current VM tools version query:

You can query with the virtual machine name to assign it to the correct customer.

`https://prometheus-infra.<region>.cloud.sap/api/v1/query?query=group by (virtualmachine, project, guest_tools_version) (vrops_virtualmachine_guest_tools_version{virtualmachine=“<vm name>“}) AND on (virtualmachine) (vrops_virtualmachine_runtime_powerstate{state="Powered On"})`

You can also use it multiple times: 

`https://prometheus-infra.<region>.cloud.sap/api/v1/query?query=group by (virtualmachine, project, guest_tools_version) (vrops_virtualmachine_guest_tools_version{virtualmachine=“<vm name>|<vm name>|<vm name>|...“}) AND on (virtualmachine) (vrops_virtualmachine_runtime_powerstate{state="Powered On"})`

Or with project id: 

`https://prometheus-infra.<region>.cloud.sap/api/v1/query?query=group by (virtualmachine, project, guest_tools_version) (vrops_virtualmachine_guest_tools_version{project=“<project id>“}) AND on (virtualmachine) (vrops_virtualmachine_runtime_powerstate{state="Powered On"})`

Example: 

`https://prometheus-infra.<region>.cloud.sap/api/v1/query?query=group by (virtualmachine, project, guest_tools_version) (vrops_virtualmachine_guest_tools_version{virtualmachine=“ccd06-shp-nucleus-k8s-worker1-4kf78 (2ae68eb4-761e-4e08-b9d6-618a6a19d374)“}) AND on (virtualmachine) (vrops_virtualmachine_runtime_powerstate{state="Powered On"})`

response:
```json
{
  "status": "success" ,
  "data": {
    "resultType": "vector" ,
    "result": [
      {
        "metric": {
          "guest_tools_version": "0" ,
          "project": "6aecfb7bb0084f70b7fbe3b08bb7e0b5" ,
          "virtualmachine": "ccd06-shp-nucleus-k8s-worker1-4kf78 (2ae68eb4-761e-4e08-b9d6-618a6a19d374)"
        } ,
        "value": [
          1638959185.577 ,
          "1"
        ]
      }
    ]
  }
}
```

The target version will change over time. So you can update the recommended threshold with the following query: 

`https://prometheus-infra-collector.eu-de-1.cloud.sap/api/v1/query?query=group by (guest_tools_target_version) (vrops_virtualmachine_guest_tools_target_version_info)`

response:
```json
{
  "status": "success" ,
  "data": {
    "resultType": "vector" ,
    "result": [
      {
        "metric": {
          "guest_tools_target_version": "11.3.5" 
        } ,
        "value": [
          1638959185.577 ,
          "1"
        ]
      }
    ]
  }
}
```

The link will point to [documentation.global.cloud.sap](https://documentation.global.cloud.sap/compute/image-start-customers#prerequisites-for-the-images) and will be specified by us soon. 

Feel free to ask questions to @richardtief or Rahul Bhat <bhatra@vmware.com>

**Comment by hgw77** [comment]
this is done, the only thing missing is the link to the documentation to update and install vmware tools

**Comment by bhatra** [comment]
@hgw77  @richardtief  I have the documentation ready and will get it published, its waiting last min review , so hopefully tomorrow i can come back with the links.

**Comment by bhatra** [comment]
@hgw77  please use the documentation link - https://app.developerhub.io/converged-cloud/v17.0/compute/image-vmware-tools for the overall vm tools update and install information ... we could also provide alternate links for windows and linux based OS.

**Comment by richardtief** [comment]
To have it complete, this is the right link to use for **update** and **install** Vmware vm tools. 

https://documentation.global.cloud.sap/compute/image-vmware-tools

**Comment by zhaoyy7** [comment]
The link seems to be changed to 
[https://documentation.global.cloud.sap/docs/customer/compute/os-image/vmware-vm-tools/](https://documentation.global.cloud.sap/docs/customer/compute/os-image/vmware-vm-tools)
