### ISSUE TITLE
[Networking] Missing policy entry

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1021]
We are making the call to `ip_availability` as a cloud_admin user [1]. However according to the Neutron policy it is enough to be `network_viewer` or `network_admin` [2].

Additionally we don't have a rule for this route in the Elektra policy which means that if we change the call above from cloud_admin to regular `service` we would make it available only to Keystone admins (since that is the fallback if no rule exists for a particular route). 

We should check if the call in [1] can be made with `service` instead of `cloud_admin` and then adjust the Elektra networking policy to match what we have in Neutron itself. Activate policy debugger from the env file to double check which policy Elektra is trying to evaluate for the call. We use it on the "New Floating IP" screen ( `/networking/floating_ips?overlay=new`) in the Subnets Select Box to display the available IPs per subnet.

[1] https://github.com/sapcc/elektra/blob/04eff407f70b0e4842b09f260994bc61a9f02a50/plugins/networking/app/controllers/networking/networks_controller.rb#L147
[2] https://github.com/sapcc/helm-charts/blob/93dd3b55df6461b744e6346a9b734783c0095f04/openstack/neutron/templates/etc/_neutron-policy.json.tpl#L70

**Comment by edda** [comment]
I just realized that the reason we use the cloud_admin user might be that you need to be `network_viewer` or `network_admin` in the project the network is defined in. Since the floating ip networks are usually shared from other projects we might have to keep doing the call with the cloud_admin user. But we should still add the policy entry for the route so that it doesn't fall back to the default policy (if this is what happens)

**Comment by hgw77** [comment]
https://github.com/sapcc/elektra/pull/1022
