### ISSUE TITLE
old server snapshots aren't shown

### ISSUE THREAD

**Issue by geisslet** [sapcc/elektra#1051]
Reference ticket and customer contact: INC1700409

Issue:
list of server snapshots only the snapshot from March 16 is available. Older snapshots that we had taken are no longer visible.

Investigation:
there is no limit for the snapshots expect of the object storage quota. The snapshots are also still there, but the GUI is not showing all images.

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
