### ISSUE TITLE
key manager secrets payload output modifies the payload output

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#1055]
Users cannot rely on the UI payload output, because it:
* strips `<` symbols and everything that looks like html, e.g. `bbb<foo>aaa</bar>` will look like `bbbaaa`
* replaces `>` symbol with `&gt;`, e.g. `my>pass` will look like `my&gt;pass`

![Screenshot_20220331_122150](https://user-images.githubusercontent.com/4047483/161033696-cc8c1dee-0639-4c94-ae7b-31f4a2d263f8.png)

**Comment by ArtieReus** [comment]
make sence. I will have a look
