### ISSUE TITLE
swift: asynchronous container info retrieval

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#1100]
In current implementation the main `Object Storage` page tries to list all containers and retrieve details for each of the container before rendering the page. If account has a high amount of containers, this takes a while.

I suggest to retrieve containers' information asynchronously + provide a button to refresh container info to get the recent info about the amount of objects and size.

cc @majewsky

**Comment by majewsky** [comment]
cc @hgw77

**Comment by andypf** [comment]
on it!

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
