### ISSUE TITLE
AZ resource overview must be updated for Limes API change

### ISSUE THREAD

**Issue by majewsky** [sapcc/elektra#1130]
Because of new requirements from billing/controlling, we need to change the granularity of compute subcapacities in Limes. This impacts the AZ resource overview in Elektra, specifically the part showing individual vCenters:

![image](https://user-images.githubusercontent.com/24696/193831580-b1728d99-ecd5-4a27-8cfb-a3d6fb4de408.png)

This data comes from the "subcapacities" section on the resources `compute/cores`, `compute/instances` and `compute/ram`. Currently there is one subcapacity for each AZ and each vcenter, for example:

```json
{
  "name": "vc-b-0",
  "metadata": {
    "availability_zone": "qa-de-1b"
  },
  "capacity": 400,
  "usage": 214
}
{
  "name": "qa-de-1d",
  "metadata": {
    "availability_zone": "qa-de-1d"
  },
  "capacity": 2120,
  "usage": 662
}
```

After the API change, there will instead be one subcapacity for each hypervisor (i.e. each building block), for example:

```json
{
  "service_host": "nova-compute-bb97",
  "az": "qa-de-1a",
  "aggregate": "vc-a-1",
  "capacity": 768,
  "usage": 587
}
```

The total capacity and usage for each vCenter can be obtained by summing up the respective values for all hypervisors with the same values for `az` and `aggregate`. To ease the migration to this new format, I've added the "az" and "aggregate" fields on the old subcapacities, for example:

```json
{
  "name": "vc-b-0",
  "metadata": {
    "availability_zone": "qa-de-1b"
  },
  "capacity": 400,
  "usage": 214,
  "az": "qa-de-1b",
  "aggregate": "vc-b-0"
}
```

So it should be possible for you to write code that works both with the old and new layout. I can provide more explanations if needed. There is also more context in the Limes PR (sapcc/limes#259). Please treat this request urgently, I will not merge the Limes PR until the Elektra change is rolled out.

**Comment by hgw77** [comment]
https://github.com/sapcc/elektra/pull/1138
