### ISSUE TITLE
shared object storage: add a way to copy the path to directory/object

### ISSUE THREAD

**Issue by SuperSandro2000** [sapcc/elektra#1134]
Right now when browsing the shared object storage there is no obvious way to copy the path to the current directory or to a file. You could select and copy the bread crumbs but they are concatenated to one long string. In the old UI they where concatenated with spaces but ideal would be a small copy button to get the path with the slash separators.

**Comment by andypf** [comment]
Done with #802b0a88137466b9d4a097740fd4a4bb79604c17

**Comment by SuperSandro2000** [comment]
Thanks for the fast implementation 🎉
