### ISSUE TITLE
[lbaasv2]

### ISSUE THREAD

**Issue by notandy** [sapcc/elektra#1135]
Secret selection from barbican doesn't show all certificates.

Barbican secret selection when creating a listener is not showing all certificates, because the api is paginated by default.

Example: https://dashboard.qa-de-1.cloud.sap/monsoon3/cc-demo/lbaas2/?r=/loadbalancers/3ea4927d-5667-4531-9551-be72b7b17911/listeners/6c519f1d-a4fb-4f79-9d1a-b4f3afb7eaa8/edit

**Comment by ArtieReus** [comment]
Fixed #1140
