### ISSUE TITLE
[email-plugin]: convert all CoffeeScript files to vanilla javascript.

### ISSUE THREAD

**Issue by ArtieReus** [sapcc/elektra#1157]
We are in the process on migrating all coffee script files to agile the deployment and coffeescript seems to have lint issues with the linter.

**Comment by sirajudheenam** [comment]
This PR [PR](https://github.com/sapcc/elektra/pull/1162) : Decaffeinate elektra #1162 solves this.
 
[File Changed](https://github.com/sapcc/elektra/pull/1162/files#diff-a6c8420dd8a88bcd703a088ccf39529ef9ad4280ea547833baf01e3a1d1f4d75)
