### ISSUE TITLE
new object storage plugin - create folder sets wrong content-type

### ISSUE THREAD

**Issue by reimannf** [sapcc/elektra#1178]
Creating a new pseudo-folder within a container with the new object storage UI a wrong additional `content-type` ist set on the object.

You can check in `qa-de-1/ccadmin/master` project the following:

```
$ swift stat repo test/
swift stat repo test2/
               Account: AUTH_xyz
             Container: repo
                Object: test/
          Content Type: application/directory, application/json
```          
The additional `content-type: application/json` is wrong and break the static web listing: https://repo.qa-de-1.cloud.sap/test/

A pseudo folder created through the old UI looks as follows:
      
```
$ swift stat repo test2/
               Account: AUTH_xyz
             Container: repo
                Object: test2/
          Content Type: application/directory
```
Here also the web listing is working: https://repo.qa-de-1.cloud.sap/test2/  

Could you please fix the `application/json` content-type?

**Comment by andypf** [comment]
fixed with 42711c9f180c22561e5be462acee16d07d748a85
