### ISSUE TITLE
Copy to clipboard in universal search does not work

### ISSUE THREAD

**Issue by SuperSandro2000** [sapcc/elektra#1187]
When trying to copy something from the universal search (eg https://dashboard.eu-de-1.cloud.sap/ccadmin/cc-tools/#/universal-search/457bef6ab24a4a348562f51e8b9d6449/show) it does not get copied.
When spamming the copy button and by accident selecting some text, it gets copied but it is usually the wrong text.
Tested in Firefox and Chrome.

**Comment by hgw77** [comment]
Tested it with Chrome on Windows 11 and it is working

This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
