### ISSUE TITLE
DNS: No error message shown when parent zone of subzone is deleted

### ISSUE THREAD

**Issue by galkindmitrii** [sapcc/elektra#1196]
Designate does not allow deletion of parent zone as long as subzones exist.
In case a user tries to delete a parent zone via CLI a correct error is shown:

> "Please delete any subzones before deleting this zone"

If this is done in Elektra - no error message is shown at all. This is very misleading for the users.

**Comment by hgw77** [comment]
can you explain how I create a subzone in elektra? I did not find an example where a zone contains a subzones

**Comment by galkindmitrii** [comment]
> can you explain how I create a subzone in elektra? I did not find an example where a zone contains a subzones

if parent zone is called **example.com.**, then subzone is **sub.example.com.**
This is especially misleading when the parent zone and subzones are in different projects.

**Comment by hgw77** [comment]
I investigated the problem and i seems Elektra does not show the error message from the API. The API returns with error 400 and the message `Please delete any subzones before deleting this zone` we need to handle the error message correctly
