### ISSUE TITLE
User search in cloudops should be the same as in openstack cli

### ISSUE THREAD

**Issue by bbobrov** [sapcc/elektra#1198]
Steps to reproduce:
1. Create or pick a project
2. Create a technical user, but do not sign in with it
3. Go to role assignments in the cloudops tools (`/<admin domain>/<admin project>/cloudops#/project-role-assignments`)
4. Search for the project, then try to add the technical user into it. Search for the user by name or id

Expected: The user is visible in the search results list
Observed: The user is not in the search results list

You can even add the user by id, if you ignore the lack of results and just press "Add", the action will succeed.

Why does it happen?

Probably because Elektra uses the equivalent if `openstack user list` and then searches for the user in that list. If the (technical) user never signed in, it might not be there.

How to fix it?

Take a look at `openstack user show --domain <domain> <name or id> --debug`. `openstack` cli makes 2 requests like this:

1. Check for the user by id
`REQ: curl -g -i -X GET https://identity`**`/v3/users/<name or id>`**` -H "Accept: application/json" -H "User-Agent: python-keystoneclient" -H "X-Auth-Token: {SHA256}token"`

2. Check for the user by username
`REQ: curl -g -i -X GET https://identity`**`/v3/users?domain_id=<domain_id>&name=<name or id>`**` -H "Accept: application/json" -H "User-Agent: python-keystoneclient" -H "X-Auth-Token: {SHA256}token"`

**Comment by ArtieReus** [comment]
Hallo @bbobrov! Thank you for your ticket. Elektra uses a local cache for the cloudops search which it is based on objects which have been managed while using elektra. If you want to find this new user in the cloudops search in elektra you will have to log in with that user. The Search does not use any backend that is way you can't find the user if the user hasn't been logged to elektra before.
