### ISSUE TITLE
kubernikusctl binary link text not specific

### ISSUE THREAD

**Issue by Carthaca** [sapcc/elektra#1200]
When clicking on Setup in my kubernikus cluster I get the links to download the kubernikusctl, for darwin there are 2 options: arm and amd, but the link text does not tell me what is what 😕 

![Screenshot 2023-03-01 at 15 55 12](https://user-images.githubusercontent.com/8159679/222176738-a5eea4e8-dfd1-4b22-a131-3cedfed3d0f9.png)

This is probably a low hanging fruit  to be fixed in https://github.com/sapcc/elektra/blob/2ae3c6fcf506742d516dcedfe7d5d327dc224683/plugins/kubernetes/app/javascript/widgets/app/components/clusters/setup.jsx#L35 😉

**Comment by hgw77** [comment]
congratulations for the 1200th issue ;-) and thank you for the hint

**Comment by hgw77** [comment]
![image](https://user-images.githubusercontent.com/5598283/222682307-9004f60b-b965-4260-82b6-a0122c81b692.png)

**Comment by hgw77** [comment]
![image](https://user-images.githubusercontent.com/5598283/222682925-28fb0a53-65a0-4118-bb51-f00942d43f27.png)
