### ISSUE TITLE
[swift] handle write-restricted containers

### ISSUE THREAD

**Issue by majewsky** [sapcc/elektra#1202]
We're introducing a new feature in Swift, wherein containers marked with the header `X-Container-Meta-Write-Restricted: true` have write operations restricted to cloud-admin users. This is intended for use with the backing containers for Keppel accounts, which the user is supposed to access only via the Keppel API.

When a non-cloud-admin user tries to perform a write access (PUT/POST/COPY/DELETE) on one of these containers or the objects contained therein, Swift will return a 405 (Method Not Allowed) error and provide a slightly more detailed error message in the response body:

```
$ curl -isH "X-Auth-Token: ${OS_AUTH_TOKEN}" "${OS_STORAGE_URL}/keppel-dockerhubmirror" -X DELETE
HTTP/1.1 405 Method Not Allowed
content-type: text/html; charset=UTF-8
content-length: 41
x-trans-id: tx8ae0e1bbe14a4b939e2d4-006401f72c
x-openstack-request-id: tx8ae0e1bbe14a4b939e2d4-006401f72c
date: Fri, 03 Mar 2023 13:33:32 GMT

Writes are restricted for this container.
```

Elektra currently only shows the generic name of the HTTP status code. At a minimum, it should show the error message from the response body in this situation (or a combination of the two):

![image](https://user-images.githubusercontent.com/24696/222733662-b1577004-8e6a-4383-9b97-25b11fd32b2e.png)

Ideally, Elektra would recognize the `X-Container-Meta-Write-Restricted: true` header and hide all upload/edit/delete actions on the container and the objects therein.

The Swift and Keppel changes are deployed to qa-de-*, so you can test there by going into any project that has Keppel accounts (e.g. ccadmin/master or monsoon3/cc-demo) and looking for Swift containers that start with `keppel-`.

**Comment by andypf** [comment]
fixed with e6cef1958690cf2dbe34ceb8228d95ccad2f9650
