### ISSUE TITLE
[swift] Missing support for newest versioning middleware

### ISSUE THREAD

**Issue by reimannf** [sapcc/elektra#1210]
Object versioning was recently upgraded in Swift and put the old methods through `X-Versions-Location` or `X-History-Location` headers as legacies mode.
The newest method is activated with header `X-Versions-Enabled: True` on container level. The main difference to the legacy methods is, that it stores versions in a hidden container, which is not accessible with standard Swift API.
Unfortunately I completely forgot to request some enhancements for the Object Store plugin and customers have currently no access to that versions through Elektra.

Remark: As we have already customers using the legacies modes, we should not stop supporting that.

* Container Properties Page: `X-Versions-Enabled` can be enabled here and is the preferred versioning method. The 3 different modes are of cause exclusive.
* Listing versions of a container: If `X-Versions-Enabled` there should be a listing UI (similar to the usual object listing) with all versions available for the container
   * listing versions: `?format=json&versions=true`
   * we should highlight the current version --> `is_latest`
   * we should highlight delete markers --> content-type `application/x-deleted;swift_versions_deleted=1`
   * can be an additional entry in wrench button
   * deleting and downloading of a single version should be possible
   * Delete all versions should be possible
* Deleting of `X-Versions-Enabled` containers: It is not possible to delete containers with remaining versions in the backend. The UI should point the User to the version UI if there are still versions left. 

The Swift API docs do not yet have any reference to this, but everything is documented here: https://github.com/openstack/swift/blob/master/swift/common/middleware/versioned_writes/object_versioning.py#L17-L135

**Comment by andypf** [comment]
fixed with 75a85eab29279f511c6b8c8381265c619cf8dbfe
