### ISSUE TITLE
[lbaas] Various small issues in Octavia UI

### ISSUE THREAD

**Issue by m-kratochvil** [sapcc/elektra#1219]
Found two small issues in Octavia UI.

**1.**
**Source IP persistence not being removed**
Source IP persistence can't be removed via Elektra, it stubbornly stays configured on a pool.
Removal working fine via CLI. API untested but presumed working.

Following pool can be used for testing:
https://dashboard.qa-de-1.cloud.sap/monsoon3/d071955-testing/lbaas2/?r=/loadbalancers/487e7950-d600-483c-9493-89206f2f338b/show?pool=50fb3f12-aae9-44dd-9840-594b96d8fdbf

Also tracked in f5 provider driver repository under issue sapcc/octavia-f5-provider-driver#221

**2.**
**Hover over a default pool checkmark not showing correct value**
When hovering over the default pool checkmark on the main loadbalancer screen (in the section with list of listeners), the correct default pool ID id shown, but doing the same on a specific listener screen, the hover shows different (wrong) pool ID.

Example:
Correct default pool id is shown for listener `test-listener-2` [HERE](https://dashboard.qa-de-1.cloud.sap/monsoon3/d071955-testing/lbaas2/?r=/loadbalancers/487e7950-d600-483c-9493-89206f2f338b/show)
Wrong default pool is shown for the same listener [HERE](https://dashboard.qa-de-1.cloud.sap/monsoon3/d071955-testing/lbaas2/?r=/loadbalancers/487e7950-d600-483c-9493-89206f2f338b/show?listener=d7212e7d-0e6f-4f04-b352-52801aac7c02)

Discussed both issues with @ArtieReus  on 05/30/23

FYI @BenjaminLudwigSAP

**Comment by ArtieReus** [comment]
Fixes:
https://github.com/sapcc/elektra/pull/1249
https://github.com/sapcc/elektra/pull/1248

**Comment by ArtieReus** [comment]
@m-kratochvil the fixes are deployed to QA. Would you please double check? Thx

**Comment by ArtieReus** [comment]
Tested in QA and it seems to work fine now. Closing...
