### ISSUE TITLE
Introduce the dark theme

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#1223]
Users should be able to switch to the dark theme.
In addition modern browsers support automatic switch based on the OS setting for the dark theme.

**Comment by edda** [comment]
We would like to have this, too. But unfortunately it isn't as easy to do as you might assume as Elektra's styles weren't written with a possible theme switch in mind. Which means there would have to be a lot of refactoring done before we could even think to add a dark theme. And then of course a dark theme would have to be designed in the first place. We will hopefully do this at some point but it's not gonna happen soon unfortunately...

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
