### ISSUE TITLE
[lbaas] Add Allowed CIDRs feature to UI

### ISSUE THREAD

**Issue by velp** [sapcc/elektra#1232]
We just added support for `allowed_cidrs` to our Octavia's driver implementation (https://github.com/sapcc/octavia-f5-provider-driver/pull/229). And we would like to have it in the dashboard.

API description:
- POST request for `listener` and field `allowed_cidrs` you can find [here](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-listener-detail#create-listener)
- PUT request for `listener` and field `allowed_cidrs` you can find [here](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-listener-detail,update-a-listener-detail#update-a-listener)

How to set `allowed_cidrs` for existing `listener`:

```
curl -g -i -X PUT https://<URL>/v2.0/lbaas/listeners/<LISTENER_ID> \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "User-Agent: openstacksdk/1.2.0 keystoneauth1/5.2.1 python-requests/2.31.0 CPython/3.11.3" \
    -H "X-Auth-Token: <TOKEN>" \
-d '{"listener": {"allowed_cidrs": ["10.46.22.1/24"]}}'
```

How to remove `allowed_cidrs` from a `listener` (set allow any subnets):
```
curl -g -i -X PUT https://<URL>/v2.0/lbaas/listeners/<LISTENER_ID> \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "User-Agent: openstacksdk/1.2.0 keystoneauth1/5.2.1 python-requests/2.31.0 CPython/3.11.3" \
    -H "X-Auth-Token: <TOKEN>" \
-d '{"listener": {"allowed_cidrs": ["0.0.0.0/0"]}}'
```

To update the list of CIDRs and add one more, you have to send a full list of CIDRs. For example if `listener` has `10.46.22.1/24` CIDR configured and you want to add another CIDR `10.8.0.1/24` you have to send a body with both CIDRs:

```
{"listener": {"allowed_cidrs": ["10.46.22.1/24","10.8.0.1/24"]}}
```

**Comment by ArtieReus** [comment]
Hi @velp! I will prioritise the feature request and update you once we start with it.

**Comment by ArtieReus** [comment]
Hi @velp! as far as I know this feature ist not yet roll out in production. If we implement the feature in Elektra will crush as soon as it reaches production. Please let me know when it is in production deployed. Thx!

**Comment by velp** [comment]
@ArtieReus I will start rolling on this week. And, yes, will let you know when it will be everywhere.

**Comment by velp** [comment]
@ArtieReus this PR can be merged. The backend side rolled out everywhere.

**Comment by velp** [comment]
Do you mean pass body:
```
{"listener": {"allowed_cidrs": [}}
```
instead of:
```
{"listener": {"allowed_cidrs": ["0.0.0.0/0"]}}
```
when we remove all CIDRs?

**Comment by ArtieReus** [comment]
I mean all listeners have default `null` if no CIDR set. Why should then I add a string when removing the CIDRs??
![Screenshot 2023-08-01 at 14 21 26](https://github.com/sapcc/elektra/assets/1876079/0d679f28-760d-42ec-a987-3096b31c2998)
