### ISSUE TITLE
FIP assignment for VM does not show FIP description

### ISSUE THREAD

**Issue by galkindmitrii** [sapcc/elektra#1241]
Hi,

When assigning the FIP for Octavia LB -> the description of FIP is shown in the parenthesis.
But when assigning FIP for a Nova VM -> only the IPs are shown, without description, making it harder to find the right FIP to attach.

**Comment by galkindmitrii** [comment]
Example how it looks for LBs:
<img width="546" alt="Screenshot 2023-07-13 at 12 24 04" src="https://github.com/sapcc/elektra/assets/1788175/69751168-6dfe-4491-8665-b03c5f0768bf">

**Comment by andypf** [comment]
I can't reproduce this. I have just created a FIP with description and I can see it in the compute
![image](https://github.com/sapcc/elektra/assets/2726096/7bcf5689-c490-4bb3-ada2-f6e9d8dad37c)

**Comment by galkindmitrii** [comment]
OK, found the issue:
when a LoadBalancer with FIP attached is deleted the FIP is detached and FIP description is deleted for no reason.... this is Neutron or Octavia issue.
