### ISSUE TITLE
Propagate `prodel` errors in Elektra

### ISSUE THREAD

**Issue by stanislav-zaprudskiy** [sapcc/elektra#1247]
Internal issue `/cc/prodel/issues/75`

ATM, Elektra doesn't seem to be picking up errors returned by prodel. Instead, an empty response with `HTTP 200` is returned (blank screen).

For better user experience and troubleshooting possibilities it should propagate errors returned by prodel. E.g. an error
```console
$ curl -D /dev/stderr localhost:5000/api/v1/projects/${project_id}/resources/ -H "X-Auth-Token: $id"
HTTP/1.1 500 INTERNAL SERVER ERROR
Server: Werkzeug/2.2.3 Python/3.10.7
Date: Fri, 28 Jul 2023 09:25:12 GMT
Content-Type: application/json
Content-Length: 247
Connection: close

{
  "code": 500,
  "errors": {
    "keystoneauth1.exceptions.http.InternalServerError": "Unrecognized schema in response body. (HTTP 500)"
  },
  "message": "Unrecognized schema in response body. (HTTP 500)",
  "status": "Internal Server Error"
}
```

would appear in Elektra similar to embedded UI

![image](https://github.com/sapcc/elektra/assets/10989595/4ee7c6c4-a742-4f5d-92ff-ee3ee7a4b57d)

#### API behavior 

For expected exceptions `prodel` responds with the corresponding HTTP status code (4XX-5XX), and error details available in the response body in accordance to the OpenAPI schema.

#### Reproduction

Some examples:

* `GET` with invalid project `{id}`
* `DELETE` when `resources/` are not empty
* Call with invalid token

**Comment by hgw77** [comment]
how I can reproduce a 500 error from elektra? I need that for testing

**Comment by hgw77** [comment]
ok I could reproduce the error

**Comment by hgw77** [comment]
https://github.com/sapcc/elektra/commit/03cfe6675bbb19e345efd77f3aeda8b331a8e617
