### ISSUE TITLE
"Edit Tags" not shown unless Keystone Admin(admin) role is assigned

### ISSUE THREAD

**Issue by ZhichaoTJ** [sapcc/elektra#1255]
our customer recently noticed that without keystone admin role, he is not able to see "Edit Tag" button, which does not feels right.
Per dig into recents change https://github.com/sapcc/elektra/commit/8aa499148a27026c4bffb45752568d7f8a095ee6
I can see that the role to access "Edit Tag" menu has been adjusted, but not sure why this is not working as expected. Could you please double check?

![image](https://github.com/sapcc/elektra/assets/20290937/f69eaa6b-1ce4-432b-8d5e-3405e438f0c1)
![image](https://github.com/sapcc/elektra/assets/20290937/f7c21db2-6a8d-46e6-9c45-38ffb2561e82)

**Comment by hgw77** [comment]
thank you for the hint for the change https://github.com/sapcc/elektra/commit/8aa499148a27026c4bffb45752568d7f8a095ee6
that was the right one, there was a typo in the rule

**Comment by ZhichaoTJ** [comment]
@hgw77 the issue looks persist, now customer is receiving error info below:
![image](https://github.com/sapcc/elektra/assets/20290937/032495c0-bcc0-4007-800f-0f987b65828b)

Same error is also shown for web console button which reported under issue:
https://github.com/sapcc/elektra/issues/1260

Could you please double check? Thanks!

**Comment by hgw77** [comment]
To clarify, where can you see the `Forbidden` message? When the customer click on `Edit Tag`?

The roles that you showed above are the same?
