### ISSUE TITLE
Project domain name is hard-coded

### ISSUE THREAD

**Issue by namsral** [sapcc/elektra#126]
Currently the project's domain-name `cloud.sap` is hard-coded in the project, for example:

https://github.com/sapcc/elektra/blob/605a22c969f3dd0ed36bb168367dc2f5094b978a/lib/core.rb#L18

To improve the project's portability the domain name should be made configurable through an environment variable or config file.

**Comment by edda** [comment]
Thanks for the hint. That isn't supposed to be there. We'll have a look.

**Comment by annegentle** [comment]
Okay, coming back to a devstack test environment, I think what I was seeing was unrelated to domain scoped requests. A couple of things I'm trying:
*  I changed all the `public` endpoints in the Devstack install to point to the public IP address instead of the internal IP address, which devstack uses by default. 
* I also set the `TRUSTED_IP` in the `.env` file, and then had to comment out line 51 in `config/environments/development.rb` to get the app to run. 
* Now when I use the Default region, I get this when logging in with my admin creds (built by Devstack):

```

16 17 18 19 20 21 | def self.region_from_auth_url(auth_url = ::Core.keystone_auth_endpoint)     data = /.+\.(?<region>[^\.]+)\.cloud\.sap/.match(auth_url)     data[:region]   end    def self.locate_region(auth_user, default_region =
-- | --

```

Looks related to the above, so thought I'd share.

**Comment by edda** [comment]
Thanks for the analysis, @annegentle. We also suspect these issues to be related. We have changed this so that the region is now extracted from an ENV variable instead. Could you try it again with the latest version to see if this fixes the problem for you?

**Comment by edda** [comment]
Hardcoded DNS domain removed with https://github.com/sapcc/elektra/commit/d4b84a980b1126a617ff4806960e559f88ba21ca

**Comment by annegentle** [comment]
Thanks @edda for the quick turnaround. I've incorporated the changes from the change. Now when I run `foreman start`, it's starting on `http://0.0.0.0:5000` which is already in use by keystone. I'm not sure how to make puma run the app on another port. It's definitely using the development environment. Any hints?

**Comment by namsral** [comment]
@annegentle I think you can use the PORT env variable, like so:

```
PORT=6000 foreman start
```

**Comment by edda** [comment]
@annegentle You can also add the PORT env variable to your .env file like so: https://github.com/sapcc/elektra/blob/master/env.sample#L5

**Comment by annegentle** [comment]
So close! And yet... so far. Using the `PORT=8180` env variable in the `.env` file worked to get the dashboard working again, thanks for that. Now I get an Object Not Found error.

Here's the setup:
 * Devstack `stable/ocata` branch running on a public IP address for the dashboard and public endpoints.
 * Devstack's default port values for all the OpenStack services.
 * RegionOne is the region set up in Devstack, so I think it's also the `MONSOON_DASHBOARD_REGION` and set that in the `.env` file.
 * There's also a Default domain set in the `.env` file, `MONSOON_OPENSTACK_AUTH_API_DOMAIN=Default`.

The error I see in my browser, after going to: http://184.94.253.104:8180/Default and clicking Login, is: `404 Not Found Not Found The requested URL /v3/auth/domains was not found on this server. Apache/2.4.18 (Ubuntu) Server at 184.94.253.104 Port 80`.

I wonder if I'm not going to the URL that Elektra expects for the credentials I have set up in DevStack?

**Comment by edda** [comment]
@annegentle So it looks like it's trying to find Keystone at 184.94.253.104:80 which seems weird if you are using the default port values (I believe Keystone usually runs on 5000). Have you configured the correct keystone endpoint in the `.env` file? It should be something like:

`MONSOON_OPENSTACK_AUTH_API_ENDPOINT=http://your.keystone.endpoint.com:5000/v3`

**Comment by annegentle** [comment]
It's bizarre, right? I have no idea what's causing the 80 vs 5000 port. The Devstack endpoint does not indicate a port, and here's the endpoint list for keystone endpoints, maybe something is redirecting is all I can figure:

```
+------+-----------+--------------+----------------+---------+-----------+----------------------------------------------+
| ID                               | Region    | Service Name | Service Type   | Enabled | Interface | URL                                          |
+------+-----------+--------------+----------------+---------+-----------+----------------------------------------------+
| 160...e79 | RegionOne | keystone     | identity       | True    | public    | http://184.94.253.104/identity               |
| 216...dc9 | RegionOne | keystone     | identity       | True    | admin     | http://192.168.0.22/identity_admin           |
```

And here's a paste of the rest of the error in the browser. https://pastebin.com/6gWb5yAx I'm not mixing up the region and the domain am I? The default domain seems to be monsoon3, where is that default configured?

**Comment by edda** [comment]
@annegentle Please check your `.env` file. The configuration that is relevant to keystone is this:

```
MONSOON_OPENSTACK_AUTH_API_ENDPOINT=https://your.keystone-endpoint.com/v3
MONSOON_OPENSTACK_AUTH_API_USERID=dashboard
MONSOON_OPENSTACK_AUTH_API_PASSWORD=DASHBOARD_USER_PASSWORD
MONSOON_OPENSTACK_AUTH_API_DOMAIN=Default
MONSOON_DASHBOARD_REGION=RegionOne
```

Try entering the identity endpoint (`http://184.94.253.104/identity`) into your browser. It should tell you which versions it offers. You need to take v3. The endpoint might look something like: `http://184.94.253.104/identity/v3`. This is what you need to have as the value of the `MONSOON_OPENSTACK_AUTH_API_ENDPOINT` variable.

`MONSOON_OPENSTACK_AUTH_API_USERID` is the user name of the service user you created. We need it to authenticate the user that is trying to log in. You need to make sure it has the admin role in the configured domain (in this example `Default`). Also if you later want to create additional domains it needs to be admin in all of those domains as well. `MONSOON_OPENSTACK_AUTH_API_PASSWORD` is that user's password in that domain.

In production the region would be visible in the application's DNS domain. But for it to work in dev mode you configure it in the env file. The domain is the OpenStack domain. It's the first token after the slash. So if your application runs on localhost, port 3000 and you want to log into the `Default` domain you'd go to `http://localhost:3000/Default`.

**Comment by annegentle** [comment]
Well darn. The IP address is a floating IP running on a VM that's running DevStack, and when I go to `http://184.94.253.104/identity` the internal IP address for that VM is what's listed. Hm. I'm going to think about how to configure Devstack.
