### ISSUE TITLE
[Elektra] Tags are still not viewable without admin role

### ISSUE THREAD

**Issue by ZhichaoTJ** [sapcc/elektra#1274]
hi, Hans, @hgw77 

I'd like to bring this topic to your attention again, since it has been dragging on for sometime. It has been confirmed with at least 2 LoBs that the tags are still not viewable with compute_admin role or compute_admin_wsg role.

Below is an example:

The user has compute_admin_wsg (Nova Administrator without Securitygroup Management) role assigned, and should be able to view the tags. 

![image](https://github.com/sapcc/elektra/assets/20290937/bfb409e7-2bc7-4f37-b6f4-14bcdf691692)

**Comment by hgw77** [comment]
Sorry for the delay, I did not see this issue, a fix will be available soon

**Comment by hgw77** [comment]
fixed
