### ISSUE TITLE
[Elektra][Object Storage] Fix policy (viewer rules disappeared)

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1277]
With the latest commit in the object storage plugin the rules for the `object_storage_viewer` role were accidentally deleted. We need to get them back. For extra security double check the Swift policy.

Here's the commit: https://github.com/sapcc/elektra/commit/034223924425cae92dc7e62002571d574d7f0c09#diff-c47a8c08dc52975a8cd352ebce2ef4080066ff78d91499f84c6c823d189043cc

**Comment by hgw77** [comment]
this [commit ](https://github.com/sapcc/elektra/commit/8891791af2cbd5b30cdd39f4f73691651f73273f) will hopefully fix the problem
