### ISSUE TITLE
[Hermes/Audit] Support new search across entire event

### ISSUE THREAD

**Issue by notque** [sapcc/elektra#1279]
The Hermes API now supports a full search across the event, with and without the current available parameters. 

This is required for a customer request to find detail only held in the attachments section for certain keystone events. 

https://github.com/sapcc/hermes/blob/master/docs/users/hermes-v1-reference.md

**Comment by edda** [comment]
Is this the `search` parameter?

**Comment by notque** [comment]
Yes, the search parameter takes a string and performs a full search across the event.
