### ISSUE TITLE
[Keystone / Hermes] Display role id

### ISSUE THREAD

**Issue by bbobrov** [sapcc/elektra#1289]
Usecase: as a person working on audit events, i want to view events specific to a single role, for example, `admin`.

Usually, these events are related to role addition/removal. In these cases, role id is part of audit event attachments. Now, since #1279 got implemented, they can be searched for.

However, the user still needs to find out role id to search for. This id needs to be added somewhere in Elektra.

I propose to add it near the list of roles in "User/Group Role assignment" like on the screenshot, but anywhere else would also be fine.

![Screenshot_20231114_170730](https://github.com/sapcc/elektra/assets/33933950/73b19edc-4a70-41ee-80af-7f2787736625)

**Comment by edda** [comment]
Idea: we'll display a third tab "Available Roles" in the user role assignment plugin where we list the roles, their descriptions and the IDs
