### ISSUE TITLE
Unable to change a dns zone email address

### ISSUE THREAD

**Issue by corey-aloia** [sapcc/elektra#1308]
When creating a new DNS zone, autofill added my private email address. When clicking edit, and trying to change the email address, I am unable to. Please see this screen shot for details:
<img width="1173" alt="image" src="https://github.com/sapcc/elektra/assets/35958442/787f3b94-4ee2-4929-800d-5a1fe5e896a0">

**Comment by hgw77** [comment]
fixed with commit https://github.com/sapcc/elektra/commit/56e6755a31364b66430570f315eae82ccd039c7d
