### ISSUE TITLE
'Open as cloud admin' button for resource mgmt v2

### ISSUE THREAD

**Issue by Carthaca** [sapcc/elektra#1310]
Hi,

I would like to have 
![Screenshot 2024-01-24 at 11 43 39](https://github.com/sapcc/elektra/assets/8159679/e4cee18d-8132-42c9-b17f-cc56915c370b)
in the 
![Screenshot 2024-01-24 at 11 44 13](https://github.com/sapcc/elektra/assets/8159679/faa68e67-576b-4c20-8530-1127c5fc7a76)
too

Thanks :)
Maurice

**Comment by hgw77** [comment]
Good Idea. But, there must be first resourceManagementV2 in cloudadmin ;-)
