### ISSUE TITLE
VM search only works with name

### ISSUE THREAD

**Issue by BenjaminLudwigSAP** [sapcc/elektra#1321]
## Steps to reproduce
1) Make sure a VM exists in a project
2) Navigate to the `/compute/instances` page
3) Search for the name of the VM
4) Search for the ID of the VM
5) Search for the IP address of the VM
6) Search for the status of the VM

## Expected behavior
- Step 3, 4, 5, and 6 all yield the VM as a result

## Observed behavior
- Only step 3 (search for name) yields the VM as a result

**Comment by andypf** [comment]
Fixed
