### ISSUE TITLE
[Elektra] Check live search feature in universal search - seems broken

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1327]
There's a complaint that someone couldn't find their server using the universal search, which was most likely because it was a new server and hadn't been added to the read cache yet. We have the live search feature for those cases where we query the respective OpenStack API directly but apparently this doesn't work anymore, at least not for servers. I've tried it and for me the live search also didn't work.

**Comment by andypf** [comment]
fixed with #947dda4943b9da061af69476c820adca8210913f
