### ISSUE TITLE
[Elektra] Automate Enabling a disabled Openstack user

### ISSUE THREAD

**Issue by rajivmucheli** [sapcc/elektra#1329]
Hi,

Openstack users are disabled if they havent renewed their CAM Profile or havent logged into CCloud for long, Keystone cron job disables orphan users without any roles assigned.

Automation : 
1.  need to check if the user has the right CAM profiles, ideally it should be `CC <Domain_Name> Domain Access`. We can use SPC_CC_CON CAM User to validate this or try step 2 if user login retries exceed 3-4 times or update the banner.

2. Steps to enable Openstack user via cloud_admin role:

openstack user set --enable <user_uuid>

Is the source file https://github.com/sapcc/elektra/blob/master/app/views/monsoon_openstack_auth/sessions/new.html.haml ?

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
