### ISSUE TITLE
[Bedrock] [EOV] Elektra changes for Bedrock

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1335]
Collection of things that need to be done for project Bedrock.

Bedrock customers will each get their own domain which follows a certain naming pattern (probably this will be `iaas-someID`). All the adjustments we will have to make should only be done for domains following this naming pattern. Don't hardcode name pattern but store it in a configuration.

Hide certain services/plugins via `service_available?` method: 
- [x] cost report
- [x] automation
- [x] masterdata (?)

Additional stuff:
- [x]  project wizard fip network step needs a differentiation for these specific domains and configure a fip network that doesn't follow the same naming pattern as the exisiting domains. Exact naming pattern for the network tbd
- [x] check fip validation. We used to have some validation that only allowed certain subnet ranges because others are reserved within SAP. Check if this is still enforced anywhere as for these customers it doesn't make sense to do this.

**Comment by ArtieReus** [comment]
First draft tasks:

- [ ] Ensure all navigations are aligned using the `plugin_available?` method and Ensure `primary entries` within SimpleNavigation.

- [ ] Design a domain configuration object accessible throughout the entire application. This object should encapsulate the necessary logic for all configuration types. Convert this object to JavaScript for consumption in the React apps.

- [ ] Browse routing should be secured by adding logic into the `ScopeController` redirecting the user to the domain page when trying to access to one of the disabled plugins.

**Comment by edda** [comment]
Potential open topics that need to be checked once the first actual customer use case becomes clearer:

- [ ] Are there issues with users that aren't C/D/I-users, e.g. sending emails, log in without client cert, request workflow (inquiry tool), ...

**Comment by hgw77** [comment]
Done
