### ISSUE TITLE
Replace the quota display in Elektra, which appears at the top right of every page.

### ISSUE THREAD

**Issue by andypf** [sapcc/elektra#1354]

**Comment by andypf** [comment]
It should be a discussion on how to implement this change.

**Comment by andypf** [comment]
- The display for the Quota Usage should be integrated into Elektra as a Micro Frontend (MFE) in the same manner as the new LimesUI. - The Limes team will create a corresponding new MFE for this purpose.
   Since it's a part of Limes, the new MFE should also be included in the bundle and will be offered under the entry point named 
   quotaPlugin.
- In Elektra, we integrate this using a script tag in the layout so that it's loaded on every page.

**Comment by hgw77** [comment]
This is done
