### ISSUE TITLE
feat(elektra/swift): the "Check ACLs" button returns confusing error when ACLs are not well formatted

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#1366]
Type `project1-uid: user1-id` in both read and write ACLs (mind whitespace)

Type the `Check ACLs` button.

See

> We are currently experiencing a higher latency in our backend calls. This should be fixed momentarily. Please try again in a couple of minutes.

error message.

Expected behavior: the error message must say that the ACLs are incorrect.
![Screenshot_20240612_152544](https://github.com/sapcc/elektra/assets/4047483/14aae533-b4b0-4c3c-82bf-d21f516af610)

**Comment by edda** [comment]
This is our last resort catch-all for API 500 errors. We had planned to remove this message in favor of just stating that there was a 500 error but if this is indeed the case here, that this incorrect query causes a 500 on the backend then we can't really do much. Anyway we'll have a look what's happening here.

**Comment by andypf** [comment]
We should avoid catching 500 errors and displaying a generic error message. Instead, we should display the actual error message from the API

**Comment by edda** [comment]
Will be fixed with [#1374](https://github.com/sapcc/elektra/issues/1374)
