### ISSUE TITLE
feat(elektra): Domain page - show project description in project list

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1370]
Reference: https://github.wdf.sap.corp/PlusOne/enhancements/issues/147

- [x] check if project description is included in the project list call we make for the project list, or if we can retrieve it from the cache
- [ ] design how we would display the description in the list --> @edda 
- [ ] implement feature

**Comment by hgw77** [comment]
description is available, created a branch https://github.com/sapcc/elektra/compare/master...project_description  to document this
