### ISSUE TITLE
Deprecate nova `os-floating-ips` calls to show the VM FIP on the servers page

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#1385]
The https://docs.openstack.org/api-ref/compute/?expanded=list-hypervisors-detail%2Ccreate-server-detail#list-floating-ip-addresses call has been deprecated and it was also deprecated in gophercloud v2, which is used in terraform.

Now the FIP association must be done directly with the server's port ID. And with this change Elektra doesn't show the FIPs associated with the VM. Once a new terraform provider version will be released, users will start to complain on the inconsistency between terraform and UI.

See:

* https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_floatingip_v2
* https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_floatingip_associate_v2
* `openstack/compute/v2/extensions/floatingips` - This was a proxy for the Networking service, Neutron. Use `openstack/networking/v2/extensions/layer3/floatingips` instead - https://github.com/gophercloud/gophercloud/blob/master/docs/MIGRATING.md

There are two ways to identify the FIP <-> Server association:

* get `port_id`'s listing the ports with `?device_id=%server_id%`, then list `floating_ip`'s with the corresponding `?port_id=%port_id%&port_id=%port_id%`
* list `floating_ip`'s using the server's `fixed_ip`'s: `?fixed_ip_address=1.2.3.4&fixed_ip_address=4.3.2.1`. But the latter solution is less precise since there could be different networks with the same `fixed_ip_address`'es.

**Comment by m-kratochvil** [comment]
There is a customer incident similar to this issue, but for the Jenkins Openstack plugin. I thought I'd mention it here for an interesting reference: https://convergedcloud.slack.com/archives/C7D2FPEF4/p1722314007610139
