### ISSUE TITLE
[Bug](elektra): on the domain overview page both the "create project" and "request project" link are visible but only one works

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1416]
**Description**
On the Domain overview page a domain admin can see both the "create project" link as well as the "request project" link. When you click the "request project" link you get a "Forbidden" error stating you need to have the admin role. I assume this is a regression from the layout change to have the project list in two columns and all the admin functionality in just one.

**Steps to Reproduce**

1. Be a domain admin 
2. in that domain on the overview page you will see both links
3. click the "request project" link

**Expected Behavior**
Only the "create project" link should be visible to domain admins

**Screenshots**
![Image](https://github.com/user-attachments/assets/d01b4970-7cfb-4f88-87f6-a0c1850b7649)

**Comment by hgw77** [comment]
#1418 will fix the problem
