### ISSUE TITLE
Deleting a ed25519 ssh key crashes elektra

### ISSUE THREAD

**Issue by SuperSandro2000** [sapcc/elektra#1426]
**Description**

**Steps to Reproduce**

1. upload a ed25519 ssh key
2. try deleting it in the web interface

**Expected Behavior**
Delete the key

**Screenshots**
![image](https://github.com/user-attachments/assets/9bf4f523-ea46-48c7-9e9f-2bae772f1784)

**Environment**

- OS: Windows
- Browser: Chrome
- Version: 129.0.6668.90 

**Additional Context**

**Comment by SuperSandro2000** [comment]
just tried this again and it seems to work. Not sure what happened when I tried it a couple of weeks ago.

**Comment by hgw77** [comment]
👍
