### ISSUE TITLE
[Feature](dashboard): hide docs/support section and domain switcher in iaas-* domains

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1429]
Adjust dashboard landing page for the iaas-* domains:

The `iaas-*` domains have a different use case.

- [x] Hide docu/support section
- [x] Hide domain switcher
- [x] Completely hide region/domain switcher buttons
- [x] render a div with a high z-index over the worldmap and place a button "Enter" in the middle that people use to enter their chosen domain, no domain switching possible

**Comment by hgw77** [comment]
if a specific domain is configured it looks like

![Image](https://github.com/user-attachments/assets/2523ca3d-240e-4a13-b0bc-71128b60bf95)

* worldmap is not clickable
* no domain switcher
* no docu section
* no support section
