### ISSUE TITLE
[Task](elektra): make service user optional for dev

### ISSUE THREAD

**Issue by andypf** [sapcc/elektra#1456]
To avoid relying on service_user for identifying friendly IDs, we need to rework our scoping logic to ensure that the actual user is used for identifying domain and project-friendly IDs. This will require adjusting our logic so that the authenticated user’s context is prioritized, allowing for more accurate identification of friendly IDs based on the actual user’s permissions and scope.

**Comment by andypf** [comment]
Not needed anymore for now

**Comment by hgw77** [comment]
here the branch for reference if we need to go forward on that topic https://github.com/sapcc/elektra/tree/andypf-service-user
