### ISSUE TITLE
[Task](elektra-puma): ddos from object storage

### ISSUE THREAD

**Issue by andypf** [sapcc/elektra#1466]
**Task Description**

A potential vulnerability has been identified where a Bulk Delete operation in object storage could trigger a Denial-of-Service (DoS) attack through the OS proxy on Elektra.

Upon reviewing the current configuration of the Puma server, it was found that it is set to run with a default of 10 threads. This default value can be overridden using the MAX_THREADS environment variable. However, since no specific configuration for MAX_THREADS was found in the current values, the default setting remains active.

Background:

Puma utilizes an internal thread pool to handle requests. Each thread processes a single request at a time. With the default configuration of 10 threads, this means Puma can handle up to 10 requests concurrently. If more than 10 requests are received at the same time, the additional requests are queued and will be processed once a thread becomes available.

In the worst-case scenario, this can cause delays as requests remain blocked until a thread is freed up. This could also have an impact on the Liveness Probe, whose current settings might be too strict and should potentially be reconsidered in this context.

**Sub-tasks**

**Additional Context**
Slack: https://alertmanager.scaleout.eu-nl-1.cloud.sap/#/alerts?receiver=prometheus-alertmanager/route-slack/slack_by_os_service

**Comment by ArtieReus** [comment]
Region: eu-nl-1
Plugin: Shared Object Storage
Object sizes:

![Image](https://github.com/user-attachments/assets/a2e6c547-645e-4ce1-9cba-526eb7dccdf7)


Whenever an alert is triggered:
![Image](https://github.com/user-attachments/assets/0c3a0dbc-c517-452e-a864-d28a401b11b2)

Upon inspecting the Pods, I noticed that all of them are being restarted:
```bash
┗➜  k get pods
NAME                                  READY   STATUS    RESTARTS        AGE
elektra-67d9557dd7-jjc4z              3/3     Running   4 (113m ago)    18h
elektra-67d9557dd7-jsxhw              3/3     Running   69 (112m ago)   12d
elektra-67d9557dd7-kw7g8              3/3     Running   67 (109m ago)   12d
elektra-67d9557dd7-qs9ks              3/3     Running   70 (113m ago)   12d
elektra-67d9557dd7-tqnm2              3/3     Running   67 (112m ago)   12d
elektra-67d9557dd7-wmzsv              3/3     Running   28 (112m ago)   6d20h
elektra-pgbackup-556b9d8876-lzr2q     2/2     Running   0               15d
elektra-pgmetrics-567f69b44f-mbhc2    2/2     Running   0               13m
elektra-postgresql-86467ccb6c-zgtrm   2/2     Running   0               22h
session-pruning-6cfd47c446-jlpln      2/2     Running   0               12d
```

When checking the logs of the previous Pods:

```bash
k logs elektra-67d9557dd7-jjc4z -c rails --previous
```

I observed the following in the last lines:

```bash
...
[ca3d7aa7ad4c4cf31cecc04126f711fd] Processing by OsApiController#reverse_proxy as JSON
[ca3d7aa7ad4c4cf31cecc04126f711fd]   Parameters: {"bulk-delete"=>"true", "domain_id"=>"<secret>", "project_id"=>"<secret>", "plugin"=>"object-storage", "path"=>"swift"}
- Gracefully stopping, waiting for requests to finish
```

At times, the logs reveal that the server starts up but is terminated shortly after due to a surge of bulk delete requests arriving simultaneously. These requests block the liveness probe, causing the server to fail and the Pods to restart.

**Comment by andypf** [comment]
It seems like the scaling up from 4 to 6 pods solved this problem.
