### ISSUE TITLE
[Monsoon Openstack Auth] login_form_user -> failed. The resource could not be found.

### ISSUE THREAD

**Issue by YaEvan** [sapcc/elektra#151]
When I configure the .env file, foreman start run the project, visit localhost: 3000/Default, enter the login page, enter the horizon existing account, prompt
`[Monsoon Openstack Auth] login_form_user -> failed. (http://10.211.xx.xx/identity/auth/tokens): The resource could not be found.`
The "user" and "demo" account login is not up. horizon login success.

my .env config file is
`# Devstack standard admin user/pw settings used for elektra service user
MONSOON_OPENSTACK_AUTH_API_ENDPOINT=http://10.211.xx.xx/identity/v3/auth/tokens
MONSOON_OPENSTACK_AUTH_API_USERID=admin
MONSOON_OPENSTACK_AUTH_API_PASSWORD=secret
MONSOON_OPENSTACK_AUTH_API_DOMAIN=Default
DEFAULT_SERVICE_INTERFACE=public
`
openstack is build by devstack on ubuntu16.04.
I have used “http://10.211.xx.xx/identity/v3/auth/tokens” to test the keystone api, succeeded. the url from xxx.xxx.xxx.xxx/indentify.
The "admin" user is admin role.

thanks.

**Comment by YaEvan** [comment]
It must use devstack mitaka edtion, my mistake.

**Comment by edda** [comment]
Which version were you using?

**Comment by YaEvan** [comment]
@edda I was use pike，and now I use mitaka solve the problem， but when I login redirect to home, the error is #154 .Thank you for your reply.
