### ISSUE TITLE
After sign in demo user, bad URI(is not URI?)

### ISSUE THREAD

**Issue by YaEvan** [sapcc/elektra#154]
I access ` localhost:3000/Default`
After sign in use demo, redirect to Default/home, the page error show:

`URI::InvalidURIError in Identity::DomainsController#show`  

`bad URI(is not URI?): [{"region_id"=>"RegionOne", "url"=>"http://10.211.xx.xx:35357/v3", "region"=>"RegionOne", "interface"=>"admin", "id"=>"9d15f97a033e4b3999cef263e695f826"}, {"region_id"=>"RegionOne", "url"=>"http://10.211.xx.xx:5000/v3", "region"=>"RegionOne", "interface"=>"internal", "id"=>"af6fcbed74344f08bd6f7bdbc5db4514"}, {"region_id"=>"RegionOne", "url"=>"http://10.211.xx.xx:5000/v3", "region"=>"RegionOne", "interface"=>"public", "id"=>"b71fb2ab726344768e880b7f7b884199"}]

the error point is  `Service.new(api_client.send(name) ` in lib/core/api/client_wrapper.rb
the name variable is `identity`.

### my terminal show me:

```
FriendlyIdEntry Load (0.8ms)  SELECT  "friendly_id_entries".* FROM "friendly_id_entries" WHERE (class_name='Domain' and (lower(key)='default' or lower(slug)='default') and endpoint='http://10.211.55.27:5000/v3/auth/tokens' ) ORDER BY "friendly_id_entries"."id" ASC LIMIT $1  [["LIMIT", 1]]
17:19:42 rails.1 |   CACHE FriendlyIdEntry Load (0.0ms)  SELECT  "friendly_id_entries".* FROM "friendly_id_entries" WHERE (class_name='Domain' and (lower(key)='default' or lower(slug)='default') and endpoint='http://10.211.55.27:5000/v3/auth/tokens' ) ORDER BY "friendly_id_entries"."id" ASC LIMIT $1  [["LIMIT", 1]]
17:19:42 rails.1 | Completed 500 Internal Server Error in 96ms (ActiveRecord: 3.2ms)
17:19:42 rails.1 | 
17:19:42 rails.1 | 
17:19:42 rails.1 | bad URI(is not URI?): [{"region_id"=>"RegionOne", "url"=>"http://10.211.xx.xx:35357/v3", "region"=>"RegionOne", "interface"=>"admin", "id"=>"9d15f97a033e4b3999cef263e695f826"}, {"region_id"=>"RegionOne", "url"=>"http://10.211.xx.xx:5000/v3", "region"=>"RegionOne", "interface"=>"internal", "id"=>"af6fcbed74344f08bd6f7bdbc5db4514"}, {"region_id"=>"RegionOne", "url"=>"http://10.211.xx.xx:5000/v3", "region"=>"RegionOne", "interface"=>"public", "id"=>"b71fb2ab726344768e880b7f7b884199"}] excluded from capture: DSN not set
17:19:42 rails.1 |   
17:19:42 rails.1 | URI::InvalidURIError (bad URI(is not URI?): [{"region_id"=>"RegionOne", "url"=>"http://10.211.xx.xx:35357/v3", "region"=>"RegionOne", "interface"=>"admin", "id"=>"9d15f97a033e4b3999cef263e695f826"}, {"region_id"=>"RegionOne", "url"=>"http://10.211.xx.xx:5000/v3", "region"=>"RegionOne", "interface"=>"internal", "id"=>"af6fcbed74344f08bd6f7bdbc5db4514"}, {"region_id"=>"RegionOne", "url"=>"http://10.211.xx.xx:5000/v3", "region"=>"RegionOne", "interface"=>"public", "id"=>"b71fb2ab726344768e880b7f7b884199"}]):
17:19:42 rails.1 |   
17:19:42 rails.1 | lib/core/api/client_wrapper.rb:151:in `block (3 levels) in initialize'
```

### my .env file content is:

```
POSTGRES_SERVICE_HOST=localhost
POSTGRES_SERVICE_PORT=5432

# Rails development port
PORT=3000

MONSOON_DB_USER=dashboard
MONSOON_DB_PASSWORD=dashboard

# Devstack standard admin user/pw settings used for elektra service user
MONSOON_OPENSTACK_AUTH_API_ENDPOINT=http://10.211.xx.xx:5000/v3/auth/tokens
MONSOON_OPENSTACK_AUTH_API_USERID=admin
MONSOON_OPENSTACK_AUTH_API_PASSWORD=secret
MONSOON_OPENSTACK_AUTH_API_DOMAIN=Default
# openstack service endpoint interface, default internal (for local development you most likely need to set this to public)
DEFAULT_SERVICE_INTERFACE=public
```

other options is default by env.sample

--------------------------------------------------------------
the url access no error for http://10.211.xx.xx:35357/v3 and http://10.211.xx.xx:5000/v3
openstack edtion is mitaka

## Can you tell me how i should fix the probliem, thanks.

**Comment by andypf** [comment]
Hi,

please set MONSOON_DASHBOARD_REGION to RegionOne in .env
MONSOON_DASHBOARD_REGION=RegionOne

Andreas

**Comment by andypf** [comment]
Hi Ya Evan,

did you try to set the region in your .env?
MONSOON_DASHBOARD_REGION= RegionOne
That should fix this issue!

As the error says, identity can not find an endpoint in the catalog. Instead of a URL, an array of endpoints is found. This indicates that Elektra does not know the region.

BR,
Andreas

**Comment by YaEvan** [comment]
@andypf Thank you for your reply. I did not set region. I will try.

**Comment by YaEvan** [comment]
Hello @andypf,
I would like to ask if I have to set MONSOON_DASHBOARD_MAIL_SERVER and MONSOON_DASHBOARD_CAM_URL to use?

**Comment by andypf** [comment]
Hi,

If you want Elektra to send mails you should set MONSOON_DASHBOARD_MAIL_SERVER and optional MONSOON_DASHBOARD_MAIL_SERVER_PORT (default is 25).  I don't think you need MONSOON_DASHBOARD_CAM_URL but maybe @edda can give more infos.

BR,
Andreas

**Comment by edda** [comment]
If you don't set `MONSOON_DASHBOARD_MAIL_SERVER` then no mails will be sent when people use the request (inquiry) plugin. The `MONSOON_DASHBOARD_CAM_URL` stuff is for sending people to the place where they can request access. If you don't need that you can leave it empty, the only result will be that the link on the login screen will be broken.
