### ISSUE TITLE
hi dude developerS

### ISSUE THREAD

**Issue by rmros** [sapcc/elektra#157]
i was looking elektra travis,
what meaning "# Not yet implemented" ?
what things Not yet implemented?

![2017-11-13_12-33-09](https://user-images.githubusercontent.com/21344663/32717436-e00a129c-c86e-11e7-9985-f7bcb6a2a09f.jpg)

thanks

**Comment by edda** [comment]
Hi,

it means exactly what it says :) That particular test isn't implemented. Usually this happens when someone uses a generator to generate a new plugin for Elektra and then doesn't delete the autogenerated specs they don't need.
