### ISSUE TITLE
ssh public key checker does not know ed25519

### ISSUE THREAD

**Issue by vonneudeck** [sapcc/elektra#176]
When adding a new public key of the type ed25519 the interface does not accept it.
![bildschirmfoto 2018-01-08 um 17 56 30](https://user-images.githubusercontent.com/3678775/34716978-cd2b1ae6-f531-11e7-8bbd-6b9e810875ef.png)

**Comment by edda** [comment]
I'm not sure the OpenStack backend supports ed25519 type keys. Will have to find out.

**Comment by hgw77** [comment]
digging a little into the problem on two sides:

1. elektra side:
the error above comes from the keypair model validity check.  For ed25519 support in net-ssh we need to install [libsodium](https://github.com/jedisct1/libsodium) and [rbnacl](https://github.com/crypto-rb/rbnacl) or [rbnacl-libsodium](https://github.com/crypto-rb/rbnacl-libsodium)

2. openstack side:
I tried to setup the ed25519 key with the openstack client and got the error response 
````
{
    "badRequest": {
        "code": 400,
        "message": "Keypair data is invalid: failed to generate fingerprint"
    }
}
````
to be sure I used the openstack client in the right way I tried the same with an RSA key and it worked.  

Found a bugreport for the same error [here](https://bugs.launchpad.net/nova/+bug/1555521)
For my test I was using the API-Version 2.1, the installed Nova release is mitaka

**Comment by edda** [comment]
Thank you for the investigation. Since this isn't supported in OpenStack either let's not pursue this for now. If things change we can revisit...

**Comment by SuperSandro2000** [comment]
The openstack cli can now create keypairs for ed25519 keys, so elektra should be able to use them, too.

**Comment by hgw77** [comment]
Ok, sounds good, I will take a look 👍

**Comment by vonneudeck** [comment]
Even after all these years this fills my heart with joy. Thank you so much everyone!
