### ISSUE TITLE
Uncaught exception after removing MONSOON3_DOMAIN_USERS group from project

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#204]
Bug report:

I accidentally assigned MONSOON3_DOMAIN_USERS instead of admins to my project
when i removed them again Elektra first blocked for 1min or so. then I got an error. I couldn't do anything with the project anymore. every click sent me to the sentry feedback screen. After a while it came back and I got sent to the login screen...

**Comment by ArtieReus** [comment]
Reproducible. The request is timing out: "timeout of 60000ms exceeded"
