### ISSUE TITLE
Compute: Create server with a predefined fixed IP

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#206]
Currently when we create a server it gets a fixed IP assigned via DHCP. Some customers would like to choose a specific fixed IP for a new server.

In order for this to work we'll need to offer the ability to create ports with a specific fixed IP. Then at a later stage when creating a new server we offer the ability to use DHCP (default) or choose from the previously created ports.

**Comment by andypf** [comment]
It is already possible to assign a specific address for fixed IP during Interface Attachment. But what is still missing is the previous reservation of fixed IPs. So that these are no longer assigned by the DHCP server.
