### ISSUE TITLE
Compute: Server groups

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#209]
Server groups are affinity groups for servers which determine where (availability zone) a server will be spawned in relation to other servers in the same group.

1. Show for a server which server groups it belongs to and which rule is applied (affinity / anti-affinity)

2. Add a new server groups UI that allows CRUD for server groups

**Comment by edda** [comment]
Additional comments from kayrus:

1. Show a dedicated page where we can list all available server groups and their members
2. on the server page customer should see server group membership when it is available
3. when customer creates a server, he should be able to specify a server group, or even create one when there are no server groups available.

**Comment by kayrus** [comment]
> Show for a server which server groups it belongs to and which rule is applied (affinity / anti-affinity)

BTW, there are more profiles available: https://github.com/sapcc/nova/blob/stable/mitaka-m3/nova/scheduler/utils.py#L310..L311

**Comment by kayrus** [comment]
Another related filtering feature, which would be appreciated, when the project contains dozens on servers:
* server [tags](https://developer.openstack.org/api-ref/compute/?expanded=list-servers-detail) filter https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#id23

**Comment by hgw77** [comment]
closed because it is more than a year without activity
