### ISSUE TITLE
i read elektra readme , 

### ISSUE THREAD

**Issue by rmros** [sapcc/elektra#222]
i read elektra readme , 
its said have these features:
Extended services:
SAP Automation as a Service
SAP Hana as a Service
SAP Kubernetes as a Service

is it work for me after install elektara ?  or its private repository ? how i can access to that?

**Comment by edda** [comment]
Those are extra services we offer in our cloud that aren't part of OpenStack. Hana as a Service is proprietary. Automation as a Service is currently still in a private repo. Kubernetes as a service can be found here: https://github.com/sapcc/kubernikus, the UI for it is part of Elektra at the moment.

**Comment by rmros** [comment]
@edda i want to access Automation as a Service repo

**Comment by edda** [comment]
Sorry, we can't give you access to that one. It is very likely that the Automation service will be open sourced at some point though.

**Comment by rmros** [comment]
thank @edda 
can u suggest me some name of very likely Automation service? i want use that instead of yours automation in elektra

**Comment by edda** [comment]
A deep integration as we have it will require a lot of custom coding, like we did for our automation service. What our automation service does is register a server with our automation backend which can then be used to remote control automations on the server from Elektra via a chef client. All of that is custom code.
