### ISSUE TITLE
Networking: Rework Router UI

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#223]
The router UI needs some love. Some actions aren't possible from Elektra (e.g. removing internal interfaces) and are not named the way they are named in OpenStack.

Investigate what we should support and redesign the UI accordingly. Might be worth to separate the actions to add/remove the internal interfaces on the subnets from adding/removing the gateway interface on the FIP/External network.

**Comment by andypf** [comment]
This issue is closed due to not being active.
