### ISSUE TITLE
Ports UI enhancements

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#235]
Unify ports and fixed IP UI. Add possibility to delete ports.

Fixed IP reservations are ports with a fixed IP that haven't been attached to anything yet. In order to make this clearer to the user we'll unify the ports and fixed IP reservation UIs.

**Comment by kayrus** [comment]
It would be great if the following requests could be implemented as well:

* Add a pagination feature for the ports page
* Add network name instead/along with the network id
* "Load next" button leaves the "Loading" animation in case when it reaches the last page
![electroportsbug](https://user-images.githubusercontent.com/4047483/38390088-8fc6f318-3920-11e8-8b5c-59c74230745b.png)
