### ISSUE TITLE
Automation button on new instance form doesn't work correctly

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#250]
* `User data` doesn't appear and the error message appears
* After several reties, `User data` finally appears, but error messages don't disappear
![electrobug](https://user-images.githubusercontent.com/4047483/38389881-fc2a1ec8-391f-11e8-8149-d8bb106c9b6e.png)

**Comment by ArtieReus** [comment]
Not reproducible.
The error message appears because the automation service was probably at that time unavailable. Disabling the button prevents appearing the error message multiple times.
