### ISSUE TITLE
[LBaas2]: Filter out private IP, which are not related to the LB's network

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#254]
All floating IPs are actually visible, which could confuse users, when they select wrong IP and it won't work.
![electronetbug3](https://user-images.githubusercontent.com/4047483/38390023-5b6c4cda-3920-11e8-83d3-3b0e9f0c9d77.png)

**Comment by ArtieReus** [comment]
@kayrus I presume this is still happening in the new LBaas2 plugin. Would you please share more information please.

**Comment by kayrus** [comment]
@ArtieReus if a member IP is from a foreign private network, then it cannot be accessible from a loabalancer. Therefore the VMs list must not suggest private IPs from a foreign private network.
