### ISSUE TITLE
Rename "Terminate" instance to "Delete" instance

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#257]
Default openstack Horizon UI uses "Delete" term. "Delete" term is used in 99% of cases, why here "Terminate" is used? Was it done by purpose?
![electroterminate](https://user-images.githubusercontent.com/4047483/38390196-da8f9436-3920-11e8-98a3-855cd22ff6be.png)

**Comment by edda** [comment]
Elektra is not Horizon :) The term "terminate" is not uncommon. AWS e.g. also uses "terminate"

**Comment by kayrus** [comment]
It is still not quite clear for me why do we "Remove" cluster, port or network, but "Terminate" the server?
