### ISSUE TITLE
ObjectCache: Add ObjectCache-powered search to end-user views

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#278]
The ObjectCache-powered universal search works so well we should add it to end-user facing pages as well.

* Add universal search to project pages (results filtered by project ID). 
* Add universal search to domain start page (visible for user who have the role cloud_support_tools_view, results filtered by domain id)

**Comment by andypf** [comment]
fixed with commit 203c4b647d0cda8104dc8742817db017f7a94bd1
