### ISSUE TITLE
Automation window clears up after ~8 minutes

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#280]
Open the automation window list, wait for 8 minutes and you'll get an empty window. See the screenshot.
![screenshot_20180504_103536](https://user-images.githubusercontent.com/4047483/39619272-8482c41e-4f87-11e8-8bb7-ddb1dad0b54d.png)

**Comment by ArtieReus** [comment]
@kayrus can you still reproduce this issue. I'm not able.
