### ISSUE TITLE
Elektra posted to the wrong openstack authentication API endpoint

### ISSUE THREAD

**Issue by desdulianto** [sapcc/elektra#282]
Hello, I just posted here because I don't know where to post for the problem.

I have an development installation and already configured the .env file according to the documentation.

MONSOON_OPENSTACK_AUTH_API_ENDPOINT was set to http://x.x.x.x/identity/v3/auth/tokens

The log confirms this by printing:

 Auth Endpoint http://x.x.x.x/identity/v3/auth/tokens

But then when we access http://x.x.x.x:3000/Default/home, it says

"POST /v3/auth/tokens HTTP/1.1\r\nContent-Type: application/json\r\nAccept: application/json\r\nConnection: keep-alive\r\nUser-Agent: Elektron/2.0.0\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: x.x.x.x\r\nContent-Length: 178\r\n\r\n"

and the result is:

"HTTP/1.1 404 Not Found\r\n"
"Date: Sun, 06 May 2018 13:34:13 GMT\r\n"
"Server: Apache/2.4.18 (Ubuntu)\r\n"
"Content-Length: 290\r\n"
"Connection: close\r\n"
"Content-Type: text/html; charset=iso-8859-1\r\n"
"\r\n"

we can confirm that the endpoint is valid, by listing using openstack endpoint list:

+----------------------------------+-----------+--------------+----------------+---------+-----------+-----------------------------------------------+
| ID                               | Region    | Service Name | Service Type   | Enabled | Interface | URL                                           |
+----------------------------------+-----------+--------------+----------------+---------+-----------+-----------------------------------------------+
| 1c3c21f57aec4a43b9fc501a80f1d5ef | RegionOne | glance       | image          | True    | public    | http://x.x.x.x/image                     	 |
| 416341c36dc741b29f4bfb389230f0a5 | RegionOne | placement    | placement      | True    | public    | http://x.x.x.x/placement                 	 |
| 8868340bbf774f11be0c9f4255a379ce | RegionOne | cinderv3     | volumev3       | True    | public    | http://x.x.x.x/volume/v3/$(project_id)s  	 |
| 92b34ce0cfca4102affedfb4e5847ba6 | RegionOne | keystone     | identity       | True    | public    | http://x.x.x.x/identity                  	 |
| 973950c93fd547dca27386f95dc55440 | RegionOne | neutron      | network        | True    | public    | http://x.x.x.x:9696/                     	 |
| a9a07f530405474ca92254a7aba0b09a | RegionOne | nova         | compute        | True    | public    | http://x.x.x.x/compute/v2.1              	 |
| ad711eec0e784939861b4b68cf2936f1 | RegionOne | keystone     | identity       | True    | admin     | http://x.x.x.x/identity                  	 |
| bb07fe39bb834bc7b27b20422aa3f479 | RegionOne | cinder       | block-storage  | True    | public    | http://x.x.x.x/volume/v3/$(project_id)s  	 |
| d5f2665ed23c45f4b81d40d2868b45e0 | RegionOne | cinderv2     | volumev2       | True    | public    | http://x.x.x.x/volume/v2/$(project_id)s  	 |
| f4d57b9fefd041648f2835efe088700b | RegionOne | cinder       | volume         | True    | public    | http://x.x.x.x/volume/v1/$(project_id)s  	 |
| f63e92670dd04d868afcb58dfce24e98 | RegionOne | nova_legacy  | compute_legacy | True    | public    | http://x.x.x.x/compute/v2/$(project_id)s 	 |
+----------------------------------+-----------+--------------+----------------+---------+-----------+-----------------------------------------------+

and also by directly accessing http://x.x.x.x/identity/v3/auth/tokens from browser:

{"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}

It is a configuration error or something else?

Thanks,
Des

**Comment by ArtieReus** [comment]
Hi Des Dulianto,
did you tried to using curl? Using following command:

`curl -X POST --insecure -H"Content-Type: application/json" "https://xxx/v3/auth/tokens" -d '{ "auth": { "scope":{"project":{"id":"xxx"}}, "identity": { "methods": ["password"], "password": { "user": { "id": "xxx","password": "'$PASSWORD'" }}}}}' -v`

you should get something like this:

`* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* We are completely uploaded and fine
< HTTP/2 201
< server: nginx/1.13.8
< date: Tue, 08 May 2018 09:22:41 GMT
< content-type: application/json
< content-length: 12152
< x-subject-token: xxx
< vary: X-Auth-Token
< x-openstack-request-id: xxx
< strict-transport-security: max-age=15724800; includeSubDomains;
<
{"token":...}`

If not, you should configure your identity (keystone) server as defined in the documentation:
https://docs.openstack.org/keystone/pike/install/

Best,
Arturo

**Comment by andypf** [comment]
Hi Des,

as you suspect, it is much easier to change the endpoint so that it does not contain a prefix in the path before the version. So, like "https: //URL/v3"

And then it is important what is in the catalog of the token. If there /identity/ appears as path prefix, then your change in the Identity Plugin was just right with path_prefix: /identity/v3. That's it.

Elektra uses the monsoon-auth-gem for the first, initial authentication. Thereafter, only the endpoint from the catalog will be used. And that's where elektron comes into play. This division is historical, but we plan to harmonize it in the future. Then we will also consider such issues as yours.

Until then, it is actually much easier to change the endpoint :(

BR,
Andraes
