### ISSUE TITLE
Ports: Edit dialog and security group selection

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#301]
We can select a security group for a port when we attach a new interface to an instance, but since we don't have an edit dialog for ports it's not possible to change it later. Also the server UI doesn't show which security groups are attached to which ports.

Proposal:

1. Allow security group selection on port creation on the ports UI
2. Allow edit for ports (specifically allow changes to the security group)
3. Show which security groups are attached to which interfaces (ports) in the server UI
4. Allow security group changes on interfaces (ports) from the server UI
5. Check what happens when a server's security group assignment is changed via Nova (what happens when a server has multiple interfaces. We might have to code some special sauce or at least explain to the user what will happen if they have multiple interfaces attached.

**Comment by andypf** [comment]
The first two points could be implemented without problems. This does not work so easily for the other points. The info coming from the Nova API does not contain a mapping between security group and port.

In addition, changing the security group selection via nova affects all attached ports. :(

**Comment by andypf** [comment]
Regarding the last point: I suggest we add a corresponding Notice in server edit security group UI
