### ISSUE TITLE
Elektra doesn't allow to add an interface with specific IP address

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#324]
When user wants to create a new interface and attach it on VM, he cannot specify desired IP address, i.e. 10.180.0.100, even when it is available. As a result user receives next available IP address
![screenshot_20180711_124851](https://user-images.githubusercontent.com/4047483/42567112-083f7d5e-8509-11e8-9fee-2d54fb19eb47.png)
![screenshot_20180711_124915](https://user-images.githubusercontent.com/4047483/42567113-085daee6-8509-11e8-8582-62198d83700b.png)

**Comment by edda** [comment]
Can you please go into more detail on this? You select "Attach interface" on a server, then fill in the server fixed ip field but the interface gets an auto assigned ip instead of the one you entered? Is that correct?

**Comment by kayrus** [comment]
that is correct

**Comment by andypf** [comment]
fixed!
