### ISSUE TITLE
Elektra has to segregate ports (interfaces) and IP aliases

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#325]
1st case - two network interfaces. They could be managed by Elektra.

```
$ openstack port list --server test
+--------------------------------------+------+-------------------+----------------------------------------------------------------------------+--------+
| ID                                   | Name | MAC Address       | Fixed IP Addresses                                                         | Status |
+--------------------------------------+------+-------------------+----------------------------------------------------------------------------+--------+
| 934e0c6d-76d5-463a-bd36-a799536e13cf |      | fa:16:3e:d6:e9:87 | ip_address='10.180.0.15', subnet_id='7270e56e-c02b-4741-8403-6cee4caa21db' | ACTIVE |
| ce617140-aef5-44f1-aae4-f48a6c3da8b1 |      | fa:16:3e:3f:c2:fb | ip_address='10.180.0.17', subnet_id='7270e56e-c02b-4741-8403-6cee4caa21db' | ACTIVE |
+--------------------------------------+------+-------------------+----------------------------------------------------------------------------+--------+
```

Elektra shows:
![screenshot_20180711_125212](https://user-images.githubusercontent.com/4047483/42567188-3f0e5a76-8509-11e8-9af0-42bb72f0cc8e.png)

2nd case - two IP addresses on the port. Here we have some problems.

```
$ openstack port set --fixed-ip subnet=7270e56e-c02b-4741-8403-6cee4caa21db,ip-address=10.180.0.100 934e0c6d-76d5-463a-bd36-a799536e13cf
$ openstack port list --server test
+--------------------------------------+------+-------------------+-----------------------------------------------------------------------------+--------+
| ID                                   | Name | MAC Address       | Fixed IP Addresses                                                          | Status |
+--------------------------------------+------+-------------------+-----------------------------------------------------------------------------+--------+
| 934e0c6d-76d5-463a-bd36-a799536e13cf |      | fa:16:3e:d6:e9:87 | ip_address='10.180.0.100', subnet_id='7270e56e-c02b-4741-8403-6cee4caa21db' | ACTIVE |
|                                      |      |                   | ip_address='10.180.0.15', subnet_id='7270e56e-c02b-4741-8403-6cee4caa21db'  |        |
| ce617140-aef5-44f1-aae4-f48a6c3da8b1 |      | fa:16:3e:3f:c2:fb | ip_address='10.180.0.17', subnet_id='7270e56e-c02b-4741-8403-6cee4caa21db'  | ACTIVE |
+--------------------------------------+------+-------------------+-----------------------------------------------------------------------------+--------+
```

Elektra shows:

![screenshot_20180711_125402](https://user-images.githubusercontent.com/4047483/42567271-84850366-8509-11e8-97f8-dc8f7eaf425e.png)

Now lets assume that we never saw this project not aware what is the IP alias and what is the interface. I'm going to remove `10.180.0.100` IP interface via Elektra:

![screenshot_20180711_125620](https://user-images.githubusercontent.com/4047483/42567370-d268b55a-8509-11e8-8b6d-ad7acb0cd940.png)

And now we get only one IP 10.180.0.17, which is inaccessible.

![screenshot_20180711_125652](https://user-images.githubusercontent.com/4047483/42567390-e571be80-8509-11e8-9166-4880ae09b301.png)

It is accessible only after the reboot.

**Comment by edda** [comment]
So to summarize, we should try to find a way to somehow visualize when multiple IPs are on the same port, ideally also in the "Detach Interface" dialog. 

But the problem that the server becomes inaccessible until rebooted seems weird. Maybe the second interface never properly worked in the first place?

**Comment by kayrus** [comment]
> the second interface never properly worked in the first place
exactly

**Comment by hgw77** [comment]
closed because it is more than a year without activity
