### ISSUE TITLE
Automation: it is possible to run automation on an offline node and still get a successfully executed message

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#333]
A customer has reported that it's possible to execute automations on offline nodes.

Step by step:

Add a VM to the automation and turn it off after seeing it in Elektra - Automation Node.
Create an automation job, if there isn't any, and execute against the offline node.
Expected result - message restrict automation run to a running node.
Actual result - the automation run with a message:
mcafee successfully executed. See all runs on the Automations tab. Show details for this run.

although, the execution run report a failure.

**Comment by ArtieReus** [comment]
This is not a bug. It works as designed. The message it just says that the automation is "successfully executed", it doesn't say anything about the end state of it. May be we could make the text more understandable. I will also study the possibility to check the instance state before executing the automation.
