### ISSUE TITLE
[cloudops] role assignment - swiftreseller should be considered as cloud_admin role

### ISSUE THREAD

**Issue by reimannf** [sapcc/elektra#334]
The `swiftreseller` role allows access to all swift accounts. It should therefore be considered as a `cloud_objectstore_admin` permission, although not named correctly for historical reason.

It should not be selected when using the button `Select Admin Roles`. 

<img width="902" alt="screen shot 2018-08-03 at 09 58 00" src="https://user-images.githubusercontent.com/10754110/43632017-2a92201a-9705-11e8-8837-bf9fea5327e3.png">

**Comment by hgw77** [comment]
`swiftreseller` role no longer existing
