### ISSUE TITLE
Cloudops: Add ASR router Info and Sync UI

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#339]
Add a new cloudops application for the new ASR API. For now only the get requests + Router sync button if necessary.

API doc here: https://github.com/sapcc/asr1k-neutron-l3/blob/master/DRIVER_README.md#asr1k-apis

For now we agreed to add buttons for all the **GET** requests. Result is json, just use our existing json pretty-renderer to render the result. If `GET /asr1k/routers/[router-id]` returns an empty array, everything is fine (this means no diff between Neutron and ASR), but if this returns a json with more stuff in it it means the router needs to be synched. In that case display a "Sync router" button which does `PUT /asr1k/routers/[router-id]`.

I think it would make sense to include this in the universal search:

1) user searches for router
2) user clicks on router and gets modal overlay info with router info
3) Add new tab here named `ASR Info` which contains the new application

Note: Currently the policy for this API requires the user to be `cloud_network_admin` in the current project context (so in this case the cloud_admin project). This could be changed to just require cloud_admin (abattye can change this for us) which might be easier since assigning yourself the cloud_network_admin role is quite dangerous, if people make a mistake here they can screw up a lot of things. Another possibility would be to add another button "assign myself permissions" or something where we can at least control that the role is added only in the cloud_admin project and not elsewhere.

**Comment by andypf** [comment]
fixed with commit 7818b1cf037e82348f64e66e83862d2d0cd88b16
