### ISSUE TITLE
project request workflow is broken when cost control service is used

### ISSUE THREAD

**Issue by majewsky** [sapcc/elektra#34]
Consider a situation where the `sapcc-billing` backend service is available. A user logs on and wants to request a new project. This action happens in the domain scope, where Keystone does not deliver a service catalog. Therefore, [`services.cost_control.available?`](https://github.com/sapcc/elektra/blob/ce4d596e6f1f029d06e55b87d97cad1a397c3cb2/plugins/cost_control/app/services/service_layer/cost_control_service.rb#L15) is false and the project request form (and thus, the project request) will [not contain the form fields](https://github.com/sapcc/elektra/blob/ce4d596e6f1f029d06e55b87d97cad1a397c3cb2/plugins/identity/app/views/identity/projects/shared/_form.html.haml#L23) for specifying a cost object.

This leads to funny crashes when the domain admin tries to approve the request, because the dialog gets confused over cost control being enabled on the one side, but the request not containing any cost object data on the other side.

There are two questions in here:

1. How can we rewrite `services.cost_control.available?` such that it gives the correct result when the project request wizard is rendered?
2. When the request is approved, the dashboard seems to understand that cost control is enabled (as evidenced by it trying, and failing, to access the cost object metadata in the request). But that workflow also happens in domain scope, where `services.cost_control.available?` should give the same, wrong result. How does that work? (Maybe it just doesn't check the service availability at all?)

Since this breaks the project request workflow for customers, it would be nice if someone could look into this soon.

**Comment by edda** [comment]
We will rework the project creation flow in the coming weeks. This particular issue won't be a problem anymore then. For now, since the billing service is still pretty shakey, I think the only thing that might be worth doing is not making the cost object mandatory for project creation.

**Comment by auhlig** [comment]
Ugh :unamused:  I'll create the PR during the evening to disable this

**Comment by majewsky** [comment]
@auhlig I've lost track of this. Is this issue fixed?

**Comment by auhlig** [comment]
It should be resolved.
I remember submitting a PR and then the new project create workflow was introduced as mentioned by @edda.
Also @andypf worked on this.

**Comment by andypf** [comment]
I think it's fixed. At least it works for all the newly created projects in the last days :).

**Comment by auhlig** [comment]
Thanks for confirming.
Closing. Please reopen if necessary.
