### ISSUE TITLE
Show notification message after new Designate roles are rolled-out

### ISSUE THREAD

**Issue by galkindmitrii** [sapcc/elektra#354]
It would be great to show a small hint/message when user opens DNS page in Elektra. Text could be like: "Please review user role assignments as new DNS roles are now live. More info: URL"

The URL will be provided shortly.

Thanks,

CC @dhoeller @andypf

**Comment by andypf** [comment]
fixed with commit fa6f2570e1db40912e046e9a8057170b50aa8340
