### ISSUE TITLE
Allow users with 'cloud_dns_ops' role to assign other (less privileged) DNS roles to users 

### ISSUE THREAD

**Issue by galkindmitrii** [sapcc/elektra#355]
This is a bit tricky feature request from GNS DNS.
The DNS role hierarchy will soon look like:

cloud_dns_admin (the most privileged)
cloud_dns_ops
cloud_dns_support
dns_zonemaster
dns_hostmaster
dns_mailmaster
dns_webmaster
dns_viewer (the least privileged; read-only access)

Where only _dns_viewer_ and _dns_webmaster_ roles will be assignable via Elektra project dashboard.

Now, for GNS it will be helpful if people with _cloud_dns_ops_ role could also assign all DNS roles under (i.e. cloud_dns_support; dns_zonemaster; dns_hostmaster; dns_mailmaster; etc) to other users.

CC @andypf @dhoeller

**Comment by andypf** [comment]
fixed with commit fa6f2570e1db40912e046e9a8057170b50aa8340
