### ISSUE TITLE
Tests: Replace phantomjs with modern headless browser

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#367]
We have been running into problems with failings tests because phantomjs wasn't compatible with some of the features we use on our pages. Phantomjs isn't maintained any longer, the last release is over 2 years old. Replace poltergeist+phantomjs with a driver and headless browser that is still actively maintained and supports modern language features. 

Some quick googling points to Selenium+Chromium headless as a promising alternative. But this needs some investigation.

**Comment by ArtieReus** [comment]
@edda do we still want to make this changes?

**Comment by edda** [comment]
I think it would still make sense to do it. We haven't been writing any tests because of this problem. And investigating what to use for this nowadays is also valuable

**Comment by ArtieReus** [comment]
Fixed with #985
