### ISSUE TITLE
Compute: Floating IPs aren't displayed correctly for baremetal servers

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#372]
Floating ips can be attached to baremental servers via Elektra, but the server overview and the ip page are not displaying any floating ip afterwards. Also the detach floating ip is not working for bare metal servers, because the detach floating ip list is always empty.

The problem here is that nova doesn't deliver these infos for bm servers, only for virtual servers. We'll have to find a different way to get the information for bm servers.

**Comment by andypf** [comment]
fixed!
