### ISSUE TITLE
Add server actions on the server page

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#386]
It is hard to find the VM in huge projects. However knowing the VM id, you can open its details, e.g. https://dashboard.eu-de-1.cloud.sap/DOMAIN/PROJECT/compute/instances/INSTANCE_ID

Unfortunately this URL doesn't contain actions that are available from the servers page (i.e. VNC console, security groups modification, etc). It would be great to have these actions on the server page.

Additionaly, it would be great to access the server page by server name without knowing its id, like:

https://dashboard.eu-de-1.cloud.sap/DOMAIN/PROJECT/compute/instances/myserver

**Comment by hgw77** [comment]
this function was built in, but please use it with care, the implementation was very complicated, i have tested it as far as possible but it could be that here and there a few errors are hiding ;-)
