### ISSUE TITLE
Inquiries: Change approver check to role-based check

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#387]
Currently the list of people who can approve a new inquiry is determined at inquiry creation time and then hardcoded with the inquiry itself. This leads to several problems because it is not always reliable. Change this so that the check who can see and approve is role-based (i.e. resource-admin).

**Comment by hgw77** [comment]
I guess this will never happen, because the whole request process is very complicated, I suggest to close this issue?

**Comment by hgw77** [comment]
closed because it is more than a year without activity
