### ISSUE TITLE
Listener policies edit buttons are behind listener info section

### ISSUE THREAD

**Issue by soberano** [sapcc/elektra#400]
When viewing `> Load Balancer / Listeners / Policies` page, the policies gear menu buttons at the right side of each policy, are covered by the `Listener Info` section.
This happens when the L7 policy name is very long and doesn't have spaces in it.

Tested on Chrome (Mac) and Safari

Reproduction steps:

1. Create a load balancer with a listener.
2. Add an `L7 Policy` to the listener.
3. Type in a long name with no spaces (i.e. "_another_test_with_no_spaces_in_the_name_")
4. Complete the `L7 Policy` creation
5. Refresh the `> Load Balancers / Listeners / Policies` view - the gear menu button is shown behind the right hand side listener info box.

Workarounds:
- Zoom In (Cmd-'+') will move the gear menu away from the info box.
- When using chrome, press `TAB` until the desired gear menu button is selected.

![image](https://user-images.githubusercontent.com/1319019/48773412-f3f36480-eccf-11e8-9213-c99d2d92ed81.png)

**Comment by ArtieReus** [comment]
This is the old ui which does not exist anymore. This can be closed
