### ISSUE TITLE
yarn failes with fsevents compilation (nodejs 11)

### ISSUE THREAD

**Issue by notandy** [sapcc/elektra#414]
with following error:

> In file included from ../fsevents.cc:6:
> In file included from ../../../../nan/nan.h:192:
> ../../../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
>   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
>          ~~~  ^

**Comment by andypf** [comment]
Please downgrade node to v8.12.0 and try again

**Comment by ArtieReus** [comment]
Please see readme file to see how to install the nodjs modules:
https://github.com/sapcc/elektra/blob/master/README.md#second-install-nodejs-modules

**Comment by ArtieReus** [comment]
@notandy would you please try again. Before running yarn remove please the folder node_modules. Thx
