### ISSUE TITLE
Upgrade rails to >= 5.1.6 to get rid of security vulnerabilities

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#415]
We need to upgrade rails to the newest version to get rid of the current security vulnerabilities. This requires some extra effort because versions from 5.1.3 and above cause of redirect errors in tests (scriptr vs. script name in ActionPack).

**Comment by andypf** [comment]
Fixed with c1f0ad1f7216d8a4d09bc271ba194ae6a7ea8772
