### ISSUE TITLE
Error Handling: When a non-existent route is called we get the sentry error page instead of a nice 404

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#424]
We need to revisit error handling. Currently when a route is called which doesn't exist this leads to an uncaught exception that bubbles up all the way to the user which results in the sentry error page. Instead we should show a 404 not found message to the user.

Sometimes the error is a runtime error, e.g. try
/{domain_name}/{project_name}/networking/

Sometimes it's ActionView: Missing template, e.g. for
/{domain_name}/{project_name}/networking/ports/

**Comment by andypf** [comment]
fix the /{domain_name}/{project_name}/networking/ports/ route to accept only the json format

**Comment by edda** [comment]
Template error fixed. Reopen if we notice other cases with ugly errors
