### ISSUE TITLE
Compute: Elektra doesn't show anymore if a instance is a BM instance

### ISSUE THREAD

**Issue by B1Sandmann** [sapcc/elektra#427]
This is as @notandy suggested probably because the responsible hypervisor isn't called `nova-compute-ironic` anymore but `nova-compute-ironic-bmXXX` with X being a number between 001 and 999. For instances still in buildup  it would probably be `nova-compute-ironic-testing`.

**Comment by edda** [comment]
This seems to also affect the hypervisor stats view.

**Comment by notandy** [comment]
thanks!
