### ISSUE TITLE
Networking: private network is not shown on the routers page

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#446]
In some cases, Elektra doesn't show the private network in the private network column.

![screenshot_20190228_094718](https://user-images.githubusercontent.com/4047483/53553502-223dd700-3b3e-11e9-9e0d-5bdc237e17ed.png)
![screenshot_20190228_094734](https://user-images.githubusercontent.com/4047483/53553500-21a54080-3b3e-11e9-84be-fe2b8e56c699.png)
![screenshot_20190228_094748](https://user-images.githubusercontent.com/4047483/53553499-21a54080-3b3e-11e9-9809-208d8868eda8.png)

**Comment by andypf** [comment]
This issue is closed due to not being active.
