### ISSUE TITLE
Image: add a prerequisite caption while creating a server image/backup

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#448]
Glance uses Swift as a backend storage. For some users it is not obvious, and when there is no Object storage quota available and user creates an image, it is removed without any error messages.

I'd suggest to show a caption, warning user, if there is no quota available for the server image / snapshot.

![screenshot_20190304_095750](https://user-images.githubusercontent.com/4047483/53721698-20d51d00-3e64-11e9-973b-95f78c1970c7.png)

**Comment by andypf** [comment]
![Screen Shot 2020-10-07 at 09 28 03](https://user-images.githubusercontent.com/2726096/95300517-8f1f6400-087f-11eb-8f90-5f854f205c6a.png)
