### ISSUE TITLE
manila: share types for cloud admins

### ISSUE THREAD

**Issue by Carthaca** [sapcc/elektra#450]
Hi,

similar to 'Manage Flavors' I would like to have a 'Manage Share Types' in ccadmin/cloud_admin, where a cloud_sharedfilesystem_admin can create/read/update/delete share types, un-/set extra specs and manage access of private share types.

The api ref is https://developer.openstack.org/api-ref/shared-file-system/#share-types

This would be very helpful for manila capacity extensions. Operators would no longer need to work with the python cli, which can be difficult to handle (installation, commands, scope ...).

Perfect would be, if I can similar to Security Group Rules give a predefined parameter set for re-ocurring types, so that an operator only has to select from a set of predefined share types for creation, where most fields are pre-filled.

BR,
Maurice

**Comment by andypf** [comment]
@Carthaca Is this issue still relevant?

**Comment by Carthaca** [comment]
Thanks for checking. This is no longer relevant to me, because it can be handled via seeding with https://github.com/sapcc/kubernetes-operators/tree/master/openstack-seeder, e.g. https://github.com/sapcc/helm-charts/blob/63473b17bbfa5c6cba6c1e543ac6615e79e6dd3a/openstack/manila/templates/type-seeds.yaml and https://github.com/sapcc/helm-charts/blob/63473b17bbfa5c6cba6c1e543ac6615e79e6dd3a/openstack/manila/templates/type-assignment-seeds.yaml
