### ISSUE TITLE
Service User Authentication Error

### ISSUE THREAD

**Issue by sbikram** [sapcc/elektra#47]
Elecktra is not able to authenticate service user. I have update the .env file

I have Keystone v3 enabled in Openstack.

[root@cloud-1 ~(keystone_admin)]# openstack endpoint list |grep identity
| 6544514f28124c80a1e2ef684cfbb41e | us-west-a | keystone     | identity        | True    | internal  | http://10.9.80.50:5000/v3                    |
| c453c546636e404f8f251bab82e49c2f | us-west-a | keystone     | identity        | True    | public    | http://10.9.80.50:5000/v3                    |
| e51b95358a9f4d64b45573e50d62455b | us-west-a | keystone     | identity        | True    | admin     | http://10.9.80.50:35357/v3                   |
[root@cloud-1 ~(keystone_admin)]#

MONSOON_OPENSTACK_AUTH_API_ENDPOINT=http://10.9.80.50:5000/v3/auth/tokens
MONSOON_OPENSTACK_AUTH_API_USERID=admin
MONSOON_OPENSTACK_AUTH_API_PASSWORD=123456789
MONSOON_OPENSTACK_AUTH_API_DOMAIN=default 

when I login to Elektra UI I am getting below error

Service User Authentication Error
The request you have made requires authentication. (user_id: admin, domain: default, scope: {:domain=>{:name=>"Default"}})

When I click on Login I am able to login with the admin user however on the home it shows same above Service User Authentication Error .
![elektra1](https://cloud.githubusercontent.com/assets/6057356/23095879/c2ca431e-f637-11e6-9471-ae8e92fb5bcd.PNG)

Keystone.log

2017-02-18 18:29:33.035 4954 INFO keystone.common.wsgi [req-bdcb46e2-e8a3-4309-b9a2-998d51c9843c - - - - -] POST http://10.9.80.50:5000/v3/auth/tokens
2017-02-18 18:29:33.206 4954 WARNING keystone.common.wsgi [req-bdcb46e2-e8a3-4309-b9a2-998d51c9843c - - - - -] Authorization failed. The request you have made requires authentication. from 10.9.60.210

screenshot attached . 
![elektra](https://cloud.githubusercontent.com/assets/6057356/23095842/f70df70c-f636-11e6-86a6-b37263b7b99d.PNG)

**Comment by Carthaca** [comment]
Hi, `MONSOON_OPENSTACK_AUTH_API_DOMAIN` takes the Domain Name, so please try with `Default`

**Comment by sbikram** [comment]
Thanks for response. It was an issue with Auth Token. Keystone was not configured properly to accept domain scoped v3 API request hence it was through error when keystone was getting API request with domain in API.

**Comment by annegentle** [comment]
Hi, I think I'm seeing something similar with a stable/okata stock Devstack environment. Is there a particular configuration I need for domain scoped requests?

**Comment by edda** [comment]
Hi, the two last comments are still valid. You need to make sure to enter the correct values for your setup in the .env file. And Keystone v3 API needs to be enabled. Then it should work.

Having said that, we haven't tried this against okata yet, so there might be incompatibilities that we don't know about yet...
