### ISSUE TITLE
Elektra doesn't refresh the server status, when more than one server were created at once

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#478]
## Steps to reproduce

create at least two servers using the Elektra UI

## Current behavior

* Status animation stops spinning for the previous servers, only the latest server animation is spinning. Even after server is up and running (check via other Elektra window or CLI tool), Elektra doesn't update the status
* Even if you refresh the windows and click on the "Load next" button to see just created servers, the status is not updated. User has to refresh the servers page and push "Load next" button to see the server status.
* If user attaches the floating IP to the server, he cannot see it on the server list, servers list has to be refreshed and user has to navigate to the end of servers list pushing the "Load next" button.

## Expected behavior

Servers status has to be refreshed, when multiple servers are created via UI.

**Comment by hgw77** [comment]
this will be solved in the next iteration of the compute plugin
