### ISSUE TITLE
Hide cost report when you assign user role compute_admin_wsg

### ISSUE THREAD

**Issue by sdashpute** [sapcc/elektra#501]
Hi ccloud colleagues,

I wish to hide Hide cost report when we assign user role **compute_admin_wsg**(Nova Administrator without Securitygroup Management) in our project for group of users.

As per SPC update ticket porcessor discussed with elektra developer. 
You can see cost report when you have access to project. There is currently no option to hide this.
For this kind of access with restriction is truly required in our project for support team colleagues in production phase.
We have to rethink on customization of access type/ dashboard content as it is not required for basic access. Secondly, few section on dashboard should not be visible for basic access considering the risk.
I can show few things on screen sharing session, where delete button is visible with basic access. which is risky.

For better understanding of requirement you can contact me on s.dashpute@sap.com or skype chat /call.

Reference SPC:
https://spc.ondemand.com/open?ticket=1106049626

Regards,
Sachin D

**Comment by hgw77** [comment]
I guess this is no longer valid
