### ISSUE TITLE
Elektra doesn't show the source image ID, when the VM is booted from volume

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#510]
```
$ openstack volume create --image d66400ed-22b9-49e2-b6f7-0ec3fcacffe4 --size 16 boot-from-volume
$ openstack volume show 82a36956-0222-4daf-bbb2-6acde3def6e9 -f json -c volume_image_metadata 
{
  "volume_image_metadata": {
    "container_format": "bare",
    "min_ram": "1008",
    "vmware_disktype": "streamOptimized",
    "image_name": "my-sles12sp1",
    "image_id": "d66400ed-22b9-49e2-b6f7-0ec3fcacffe4",
    "vmware_adaptertype": "paraVirtual",
    "min_disk": "16",
    "size": "609253376",
    "hypervisor_type": "vmware",
    "hw_vif_model": "VirtualVmxnet3",
    "disk_format": "vmdk",
    "hw_video_ram": "16",
    "architecture": "x86_64",
    "checksum": "59455c1a1500ad95ee60d878650d93c0",
    "vmware_ostype": "sles12_64Guest",
    "hw_disk_bus": "scsi"
  }
}
$ openstack server create --flavor 20 --volume 82a36956-0222-4daf-bbb2-6acde3def6e9 --network afa84607-a139-4f14-b5e7-2a3df8733f88 myInstanceFromVolume
```

`OS / Size` field corresponds to `- / m1.small`

**Comment by kayrus** [comment]
Some more info about this case.

* `/v2.1/servers/detail` API call returns `image` attribute with an empty string as a value, when the VM was booted from a volume. A VM with a local storage has an object as a value.
* `/v2.1/servers/detail` API call returns attached volumes in a alphabetical order, therefore it is not possible to detect which volume is bootable, but it is possible to detect `/dev/[a-z]{2}a` device and its ID from the `/627dae2b-b5b9-4da7-9131-4457601f4b77/os-volume_attachments` call

To conclude, to show bootable VM source image name **we need two more API calls per each bootable VM**.

**Comment by andypf** [comment]
Fixed!
