### ISSUE TITLE
VM Details -> "Specs" shows flavor disk size instead of real size when "Custom root disk" is used

### ISSUE THREAD

**Issue by sku-sku** [sapcc/elektra#595]
I created an instance with the option "Custom root disk" (110 GB). The instance itself was created fine with the designated size.

If I select the VM details in the elektra dashboard and switch to "Specs", the disk size shows the size of the initially used flavor, not the real disk size.
This is misleading as the real size is not shown anywhere.

**Comment by edda** [comment]
Fixed via c081f38227b78c0a7f23d942811a2b94b01d0eab
