### ISSUE TITLE
Show cinder backups section

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#617]
It should looks like a snapshots section along volumes, e.g.

![Screenshot_20200302_214554](https://user-images.githubusercontent.com/4047483/75716312-36775f80-5ccf-11ea-9172-dacca3a36cc6.png)

**Comment by andypf** [comment]
@kayrus what is the API Call to get backups?

**Comment by kayrus** [comment]
@andypf https://docs.openstack.org/api-ref/block-storage/v3/#backups-backups

**Comment by hgw77** [comment]
closed because it is more than a year without activity
