### ISSUE TITLE
Private and shared images are not shown in create bootable volume view

### ISSUE THREAD

**Issue by VladislavAtanasov** [sapcc/elektra#646]
Hello all,

From some time ago, I am not able to see private and shared images in the dropdown in create bootable volume view( https://dashboard.eu-de-1.cloud.sap/neo/dev003_ccee/block-storage/#/volumes/new) with different users, but i am able to see them through cli and in other electra views.

BR
Vladislav

**Comment by andypf** [comment]
fixed with 6b133f9a7ad257f748b93c8bab0ba38b1e851969
