### ISSUE TITLE
422 Errors don't get shown to users

### ISSUE THREAD

**Issue by B1Sandmann** [sapcc/elektra#680]
We tried to detach a volume from a locked VM. This lead to a `{"errors":{"api":["Instance bc7b64d5-bd93-420f-8a02-3376ceb99889 is locked"]}}` but this wasn't shown to us via the elektra UI but only via developer console of the browser.

**Comment by andypf** [comment]
fixed with f44777e323ecee1e874a56677bd20846ab7dec8f
