### ISSUE TITLE
[lbaas2] Don't use deprecated Certificate/SNI containers reference

### ISSUE THREAD

**Issue by notandy** [sapcc/elektra#711]
Instead of defining Barbican Containers that contain certificate, secrets and optional immediate certificates, lbaas2 should only support secrets / certificates references directly.

Reference: https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-listener-detail#create-listener

`default_tls_container_ref (Optional) : The URI of the key manager service secret containing a PKCS12 format certificate/key bundle for TERMINATED_HTTPS listeners. DEPRECATED: A secret container of type “certificate” containing the certificate and key for TERMINATED_HTTPS listeners.`

`sni_container_refs (Optional) : A list of URIs to the key manager service secrets containing PKCS12 format certificate/key bundles for TERMINATED_HTTPS listeners. (DEPRECATED) Secret containers of type “certificate” containing the certificates and keys for TERMINATED_HTTPS listeners.`

**Comment by ArtieReus** [comment]
this look reasonable. I will fix it.

**Comment by ArtieReus** [comment]
@notandy this seems to be the same for pools:
https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-listener-detail,create-pool-detail#create-pool

**Comment by ArtieReus** [comment]
TODOs:
- Create Listener: allow just to choose secrets instead of containers when using TERMINATED_HTTPS.
- Edit Listener: existing containers should be shown but just changed by secrets.
- Same by create and edit pools
- Secrets type supported are: certificate and opaque
