### ISSUE TITLE
[Cloud shell console]: UI issue

### ISSUE THREAD

**Issue by ArtieReus** [sapcc/elektra#715]
Reported by @kayrus on Slack channel:
Cloud shell console covers the bottom of the Elektra output list. e.g. if I have a VM at the very bottom of the page, an opened cloud shell doesn't allow to click on it.

**Comment by andypf** [comment]
works as designed. You can close the console and open again.

**Comment by kayrus** [comment]
I'd reopen the issue, because closing the shell loses the shell state

**Comment by edda** [comment]
The shell doesn't lose its state when it's closed. You can close and reopen and it keeps its state.

**Comment by kayrus** [comment]
@edda apologies, you're right
