### ISSUE TITLE
Return an user friendly error when on searching the get all items return error (Search in the LB list yields only results from the currently pre-loaded list)

### ISSUE THREAD

**Issue by Finkregh** [sapcc/elektra#737]
The search in the LB list only searches in the currently displayed LBs, not all.
If you load all LBs by scrolling down etc. you will also find the LBs that are not on the first page.

**Comment by ArtieReus** [comment]
Hi @Finkregh! Thank you for your input. Are you using the old plugin or the new one?

**Comment by ArtieReus** [comment]
Hi @Finkregh, the search works as follow:
- when entering a search term the actual list of results will be filtered
- parallel will load "All" oder loadbalancers of the project and filter them out

If the searched loadbalancer is not in the list it will take a while until all other lbs are loaded. Can you please try again?

**Comment by ArtieReus** [comment]
It turned out that the background call to get all items return an error, which it is not shown to the user, and the result was not found. Change the topic to return an error if background call does not succeed.
