### ISSUE TITLE
search in server list suggests wrong behaviour

### ISSUE THREAD

**Issue by Finkregh** [sapcc/elektra#738]
Searching in the server list might lead to wrong behaviour as the text field suggests that one can enter name/ID/... w/o changing the dropdown content.
Also this was different before and should be made more explicit IMHO

![image](https://user-images.githubusercontent.com/518090/93872764-eeeb0c00-fcd0-11ea-9e21-888dbef7bcaa.png)

**Comment by andypf** [comment]
You have to select the type beforehand in the select box. @Finkregh:  What exactly do you mean? Should the placeholder text adapt to the selection of the select box?
