### ISSUE TITLE
Clicking on a server, which was provisioned from a bootable cinder volume causes an error

### ISSUE THREAD

**Issue by ArtieReus** [sapcc/elektra#742]
Text from customer:
When trying to access any server name link (that was created from a volume cinder), i am getting error 500
other servers that based on images, no issue

```
Application Error,
error (500)

Show error details 
ActionView::Template::Error
[xxxx] no implicit conversion of Symbol into Integer

There are no further details available. Sorry!
```

See Elektra Slack Channel for more details.

**Comment by andypf** [comment]
Not reproducible. Works as expected.
