### ISSUE TITLE
"Upload To Image" does not propagate some 'volume_image_metadata' properties

### ISSUE THREAD

**Issue by jeannich** [sapcc/elektra#752]
Feature "Upload To Image" that creates an image out of a volume is forgetting some volumes "volume_image_metadata" properties.

I noticed that on bootable volumes, not sure if this impacts "normal" volumes as well.

The volume_image_metadata properties that were not propagated as properties are the following:
```hypervisor_type
os-version
hw_disk_bus
hw_vif_model
vmware_adaptertype
```

**Comment by jeannich** [comment]
Interesting finding:
 Those properties **are** present when the image is in status `saving`.

When the upload is completed though, those properties disappear.


Here are below the value of "properties" extracted from command "openstack image show xxxxxxx" `during` and `after` upload.

During upload:
```
| properties       | hw_disk_bus='scsi', hw_vif_model='VirtualVmxnet3', hypervisor_type='vmware', is_public='false', os_hash_algo='None', os_hash_value='None', os_hidden='False', owner_specified.openstack.md5='', owner_specified.openstack.object='images/xy-z', owner_specified.openstack.sha256='', vmware_adaptertype='paraVirtual', vmware_disktype='streamOptimized', vmware_ostype='sles11_64Guest' |
| status           | saving
```

After upload:
```
| properties       | direct_url='swift+https://objectstore-xyz:443/v1/AUTH_xxxx/glance_xxxxx/xxxxx', os_hash_algo='sha512', os_hash_value='xxxxx', os_hidden='False', owner_id='xxxxx', vmware_disktype='streamOptimized', vmware_image_version='1' |
| status           | active
```

**Comment by andypf** [comment]
This is not a UI problem. 

Jira ticket created in m3cinder!
