### ISSUE TITLE
"Upload To Image": "visibility" and "protect this image" not working

### ISSUE THREAD

**Issue by jeannich** [sapcc/elektra#753]
Title says it all, when you use "Upload To Image" to create an image out of a volume, the resulting image will always be in "shared" visibility.
Also, the image is not in 'protected' state, no matter which option chosen in "Upload To Image" popup.

2 minor issues but still issues.

Thanks for the support

**Comment by andypf** [comment]
@jeannich I can not confirm. First of all, which Poup do you mean? There are no options available in the "Create Snapshot" popup in servers view.
The created image always ends up in "private images". The access permissions can be edited as soon as an image has been moved to shared.
