### ISSUE TITLE
[LBaas2]: loadbalancer filter doesn't work, when a target LB is created via CLI and is sorted in the displayed items

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#757]
![Screenshot_20201014_151401](https://user-images.githubusercontent.com/4047483/95994080-21031000-0e30-11eb-8c7e-3562580ac403.png)
@ArtieReus

**Comment by kayrus** [comment]
I assume this happens, when a LB is create via CLI/API and not in Elektra cache

**Comment by kayrus** [comment]
In addition if you type `*` in the search string, the JS will crash:
![Screenshot_20201014_180804](https://user-images.githubusercontent.com/4047483/96015836-4ef44e80-0e48-11eb-8414-8efc78bbd87c.png)

**Comment by ArtieReus** [comment]
The thing with the search and * is moved to a different issue #759
