### ISSUE TITLE
[Compute] Server create - root disk checkbox display problems

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#784]
In the Server create dialog the "Custom root disk" checkbox isn't aligned with the rest of the form.

![Screenshot 2020-11-13 at 13 39 39](https://user-images.githubusercontent.com/1465143/99073203-c4714d00-25b5-11eb-8ecd-1794209e0845.png)

**Comment by hgw77** [comment]
![Capture](https://user-images.githubusercontent.com/5598283/111316992-04c80100-8664-11eb-92cd-45a5048deb51.PNG)
