### ISSUE TITLE
[Images] Deep link to show a specific image doesn't work if the image is not on the initial list

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#786]
When deep linking to an image's show dialog the image isn't actually displayed if it isn't part of the initial list of images that are displayed without clicking on "Load next". 

If the image is not part of the first page, then the show dialog will only appear after clicking "Load next" enough times to make the image appear in the list.

If the image is on the initial list in a category other that "public", so e.g. if the image is shared, then the deep link will display the show dialog of the image, but the list stays on the "public" category and doesn't switch to "shared".

**Comment by andypf** [comment]
Fixed with a8f55a5bd3f96dbc77276c91bbfc16381a6534ac
