### ISSUE TITLE
[Images] private images may not be loaded

### ISSUE THREAD

**Issue by killermoehre** [sapcc/elektra#787]
Following scenario:
In the project are two private images.

What I expect:
Clicking on `Server Images & Snapshots` -> `Show: private` will list all the private images.

What I get:
After clicking on `Show: private` an empty list with a blue `Load Next` button appears. Only after clicking on this button the private images are shown.

**Comment by jknipper** [comment]
For me private images are only shown when I search for them.

**Comment by andypf** [comment]
Fixed!
