### ISSUE TITLE
[Flavour] Only show available flavours

### ISSUE THREAD

**Issue by killermoehre** [sapcc/elektra#788]
**Following scenario:**
The user selects a flavour where there is no node available to satisfy it.

**What I expect:**
The flavour is greyed out/not available.
Everything not available is greyed out.

**What I get:**
A failed server instance and the error message
```
Api: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible. <class 'nova.exception.QuotaResourceUnknown'>
```

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
