### ISSUE TITLE
SecurityGroups: DNS should be TCP+UDP

### ISSUE THREAD

**Issue by Finkregh** [sapcc/elektra#801]
The SG wizard for DNS should create rules for UDP+TCP, currently it only creates one for TCP:

![image](https://user-images.githubusercontent.com/518090/101153502-d4180a80-3624-11eb-82a7-c760980405e1.png)

**Comment by danielFoe** [comment]
I originally requested this change - but IMHO we need NO TCP rule at all - and only an egress-UDP-port53 rule  for DNS queries!

**Comment by Finkregh** [comment]
it will _also_ use TCP when the answer size exceeds the packet size, see https://tools.ietf.org/html/rfc7766

**Comment by B1Sandmann** [comment]
Bump: stumbled over this as well. I think linux can do a TCP fallback, but windows can not, and ideally it would be both.

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.

**Comment by Finkregh** [comment]
It is.
