### ISSUE TITLE
Support hypervisor_type="baremetal" for images

### ISSUE THREAD

**Issue by B1Sandmann** [sapcc/elektra#807]
Currently, images that have no `hypervisor_type` are displayed as baremetal images, images that have the `hypervisor_type="vmware"` are listed as VM images and all other `hypervisor_type` are not displayed. However, the correct tag for an baremetal image would be `hypervisor_type="baremetal"`

**Comment by B1Sandmann** [comment]
So it would be good if at some time in the future elektra would correctly display images tagged with baremetal als BM images, images taged as vmware als VM images and images with no tag as suitable for either (or maybe also BM as that is the current form). cc @BerndKue

**Comment by hgw77** [comment]
elektra is working with image information that is comming from openstack. If images correctly tagged we can adjust elektra. 

At the moment, as you said, elektra is using all images without `hypervisor_type` as baremetal images, all images that have the `hypervisor_type=vmware` are used for vm-images and all other are not shown in the create server dialog.

you can find the logic here https://github.com/sapcc/elektra/blob/master/plugins/compute/app/helpers/compute/instances_helper.rb#L39
https://github.com/sapcc/elektra/blob/master/plugins/compute/app/views/compute/instances/new.html.haml#L61-L76

**Comment by hgw77** [comment]
so from my point of view, first we need to tag all images correctly (beginning with the baremetal images) that elektra can identify the images correctly

**Comment by B1Sandmann** [comment]
So update: we are ready to tag all baremetal images, all vmware images are already tagged. The issue is, that if we now tag the baremetal images they won't get displayed in elektra till this change is in. That's why we'd like you to implement this change first. Else there will be a break for customers between us rolling out the tagged images, and you are implementing this change.

**Comment by andypf** [comment]
fixed with 600c4af83bb6915a4472becf973d2a0b8252f89b

In elektra we have grouped images with the tag "bare metal" and no tag as bare metal images. So that images with the tag "baremetal" (without spaces) are recognized as such, I have adopted the tag accordingly in elektra. Now images with the tag "baremetal" and no tag are recognized as bare metal images.
