### ISSUE TITLE
[lbaas2] Allow re-use of already assigned pool members

### ISSUE THREAD

**Issue by notandy** [sapcc/elektra#823]
A customer noticed that if a pool member VM is already selected by a pool, it vanishes from the list of available Members for other pools.

For Octavia, there is no limitation of pool members.

**Comment by ArtieReus** [comment]
Hi @notandy!
I can't reproduce this issue. Would you be so kind and describe the steps the customer used to face this issue.
Thx

**Comment by ArtieReus** [comment]
There is any news on this ticket?

**Comment by notandy** [comment]
> There is any news on this ticket?

I asked the requester to get in contact with you

**Comment by ArtieReus** [comment]
As per email explained the customer can find the host with IP address 10.18.64.47 but not the other one with 10.1.3.136. When he searches for 10.1.3.136 the list is empty. When he uses the “old/classic” UI he is able to pick 10.1.3.136. 

This is related to the closed issue #254 (Filter out private IP, which are not related to the LB's network).

@notandy Do you still think that this is an issue?
