### ISSUE TITLE
[lbaasv2] Health Monitor expected codes can't be changed

### ISSUE THREAD

**Issue by laerlingSAP** [sapcc/elektra#829]
# Steps to reproduce
1) Create a load balancer with a pool
2) Create a health monitor on said pool, e.&nbsp;g. to `8.8.8.8`, port `443`, type `HTTP`. Set expected codes to `200`.
3) Edit the health monitor. Set expected codes to `301`.

# Expected behavior
The health monitor is updated and shows the new expected code `301`.

# Observed behavior
The health monitor switches to state `PENDING_UPDATE`, but keeps the old expected code `200`

# notes
When looking at the packet dump I can see that Elektra only provides the following `health_monitor` JSON fields in its PUT request: `delay`, `max_retries`, `name`, `timeout`, `admin_state_up`.

**Comment by ArtieReus** [comment]
thx!! I will have a look

**Comment by ArtieReus** [comment]
Sorry but I can't reproduce this bahavior. Did you really used the new UI? I the new UI there isn't expected codes to be edit. The old ui will no longer be updated.

**Comment by ArtieReus** [comment]
anyway this is a field that can be updated, so i will fix it.

**Comment by ArtieReus** [comment]
A fix to be able to edit codes, http method and url path is on the way.
@laerlingSAP please forget the old ui

**Comment by laerlingSAP** [comment]
Ah, thanks. I'll try ;)
