### ISSUE TITLE
Enable search to be able to digest for partials names / patterns for volumes (and any other resource type where it not available already)

### ISSUE THREAD

**Issue by morri-son** [sapcc/elektra#836]
Hi team

different from the search for servers, the search for volumes has an issue with using just parts of a volume name. If one does not specify the exact name, the search returns nothing. Searching for patterns should be a standard feature in all search bars. That this should be there is even mentioned in the help text at the search window already: "Search by name, ID or status will find exact or partial matches..."

Gerald

**Comment by andypf** [comment]
done with 032c42ac7954a35c335fe3ca1eee4c06d10e95b8
