### ISSUE TITLE
Image selection in server-create-wizard is not preserved after error

### ISSUE THREAD

**Issue by grandchild** [sapcc/elektra#873]
When creating a server through the [Create] button, and, for example, selecting a flavor that one does not have quota for, an error is presented directly in the wizard, which is nice.

But after correcting the error, one has to select the image again, which is a bit annoying if you have to do a lot of back and forth correcting the initial error.

I'd like for the image selection to be preserved on error just as the other fields.

**Comment by andypf** [comment]
fixed with 9bb08bf86822cc89014d7dfc0a01d2e5f358d9cd
