### ISSUE TITLE
"Remove from cache" button 

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#893]
There are several views in Elektra where information is pulled from the cache. This can lead to confusion when objects that have been deleted are still available in the cache and still show up. 

For example in the network view the subnets are rendered from cache. If a subnet is deleted via CLI it won't be deleted from the Elektra cache until we run the clean up job 30 days later.

To solve this:
Add a "remove from cache" button (only for admins for now). This button should be added to the universal search UI so that objects that are returned in the search but that we know have been deleted can be removed from the cache easily.

It would be even more convenient if this button was shown on all objects that we display from cache somewhere but it's probably a lot of work to do this.

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
