### ISSUE TITLE
[Swift] Abort uploads bigger than x MiB

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#905]
The swift upload dialog has a note that only files smaller than 1 MiB are accepted and to use a different client for larger files. However it seems that this size limit is not enforced at the moment.

Fix: Abort uploads when more than 1 MiB is received. Potentially this limit can be increased a bit to max. 10 MiB. If we decide to do this, also update the note above.

**Comment by andypf** [comment]
Fixed with the new Version of Swift UI
