### ISSUE TITLE
Project Autoscaling Settings - Minimum Free

### ISSUE THREAD

**Issue by reimannf** [sapcc/elektra#906]
The project autoscaling setting on Domain level needs to be extentend by the field `size_constraints.minimum_free`.
This field has the advantage, that it works for empty, fresh projects and for projects which reduce resource usage to 0 temporarly.
It should be the first editable input field in the screen, as this is the prefered way to keep a free quota buffer on a project resource.
Nevertheless both fields (mimimum free and % free) could be entered. A hint to the user that the setting which occurs first will be executed.

The units of the resources can be retrieved directly from the domain resources context, which should already be requested. The field itself does not operate with units. But for the user it might be helpful to use the input widgets for resources we have already, which can nicely handle inputs like 5 TiB or 2MB and so on.

The `Apply to all` button should be placed above the percentage column, as it makes only sense for this field. 

The view Config by Resource can be retired, if it will not be extended.

Castellum ref: https://github.com/sapcc/castellum/blob/master/docs/api-spec.md

**Comment by majewsky** [comment]
For parsing of user inputs for values with units, the existing `Unit.parse()` method can be reused ([example](https://github.com/sapcc/elektra/blob/1ea6e5cdaa48581c6e255cdb5e741307fa828e88/plugins/resources/app/javascript/app/components/details/resource.jsx#L54-L72)).

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
