### ISSUE TITLE
Show a warning message, when incompatible keypairs are being added to user profile

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#911]
Users sometimes upload ecdsa, dss or ed25519 public keys to openstack user profile keypairs. These keypairs cannot be used to encrypt the admin password during the VM bootstrap, therefore the VM is created, but the admin password is not set (especially in case, when Windows VM is created). The only supported SSH public key type is RSA.

Elektra should warn users, when a key type is wrong:
* during the keypair creation there should be a warning
* when user selects a keypair during the server creation

It is not so harmful for non-windows VMs, because private key auth can be used in ssh. However even in Linux it is impossible to obtain the admin password to log in via VNC console, when non RSA keypair is used.

I suggest to raise the following warning:
```
Using non RSA keypair doesn't allow to set admin password at VM bootstrap
```

**Comment by hgw77** [comment]
ed25519  are now possible

This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
