### ISSUE TITLE
Add support for a new Swift Object Versioning API

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#916]
Old object versioning API is being depreceated and a new API was released as a replacement: https://docs.openstack.org/swift/latest/middleware.html#module-swift.common.middleware.versioned_writes.object_versioning

Currently Elektra still supports an old API:
![Screenshot_20210706_154022](https://user-images.githubusercontent.com/4047483/124610132-84c2e280-de70-11eb-916e-f842e0c5a565.png)

```
 $ swift stat -v versioning 
                   URL: https://objectstore/v1/AUTH_044a85a1679041b393cfec3ff0531ddb/versioning
            Auth Token: ***
               Account: AUTH_044a85a1679041b393cfec3ff0531ddb
             Container: versioning
               Objects: 0
                 Bytes: 0
              Read ACL:
             Write ACL:
               Sync To:
              Sync Key:
          Content-Type: text/plain; charset=utf-8
           X-Timestamp: 1625577329.07585
         Last-Modified: Tue, 06 Jul 2021 13:15:30 GMT
         Accept-Ranges: bytes
      X-Storage-Policy: default
    X-Versions-Enabled: True
                  Vary: Accept
            X-Trans-Id: tx18a3196c17cd42138fc65-0060e4577b
X-Openstack-Request-Id: tx18a3196c17cd42138fc65-0060e4577b
```

see `X-Versions-Enabled: True`

cc @majewsky

**Comment by hgw77** [comment]
ObjectStore Plugin was rewritten

This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
