### ISSUE TITLE
Decrypt server password directly in Elektra web UI

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#917]
Lot of customers struggle with obtaining the VM password, especially for Windows VM.
Storing RSA private keys in webshell console is not recommended, therefore we don't ship nova-password in web-shell, but customers still try to save their private key in wehshell and use `nova get-password`, which is [deprecated](https://bugs.launchpad.net/python-openstackclient/+bug/1760287) and doesn't support modern key formats.

Having a `Retrieve password` modal window like in Horizon would improve usability.
![retreive_password](https://user-images.githubusercontent.com/4047483/125934779-f8d2320f-e1f4-475b-9dbf-cb483028eabd.png)

Supporting putty keys format (https://github.com/philr/putty-key) shall be must have bonus, since most of customers work from Windows and use putty.

I expect Elektra to request customer to upload a private key, ask for a key password if it is encrypted, decrypt and show the VM password.

relates to #911

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
