### ISSUE TITLE
Sub projects list is slow, when a user has cloud admin permissions

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#919]
Cloud admins can list all projects, therefore when you open a project, the sub projects bar treis to load sub projects and it take up to 10-20 seconds:
![Screenshot_20210716_155209](https://user-images.githubusercontent.com/4047483/125958877-79387d73-45e0-41ec-acbf-2fc2fd8d898c.png)

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
