### ISSUE TITLE
HANA-flavor availability visibility in Resource Management

### ISSUE THREAD

**Issue by grandchild** [sapcc/elektra#922]
Hi Elektra Team,

We want to reflect some recent changes for BigVMs in the resource management view for the customer: 

The relevant changes in the flavors and nova are:

* The old BigVM flavors are being deprecated in favor of the NUMA-aligned `hana_*` flavors.
* For HANA flavors we introduced use Openstack _Traits_ to identify clusters that are capable of hosting them.
* We seed the HANA flavors _selectively_ in each region depending on hardware availability -- the list of public flavors not being the same in most or every region is a new situation.

So in the _Resource Management_ > _AZ_ tab, the new HANA flavors should be listed. So instead of "Available _BigVM_ resources" it should be "Available HANA VM resources". (But only if available in that region, i.e. Nova's `GET /flavors/` must mention them.)

The flavors can be matched to hosts by looking at the flavors' traits, which are mentioned in their extra-spec key `trait:CUSTOM_NUMASIZE_...`. There are two of them:
* `CUSTOM_NUMASIZE_C48_M729` for 3TiB clusters
* `CUSTOM_NUMASIZE_C48_M1459` for 6TiB clusters.

All flavors with a common `CUSTOM_NUMASIZE_*` trait should be grouped. The value for the bar should be the current per-hypervisor-size behavior for the remaining capacity (i.e. 1 or 0 more VMs possible).

(Total capacity could be calculated differently, by counting the number of clusters/resource-providers with the appropriate trait. Not sure how much sense that makes, because it's not a number of VMs, which the remaining capacity is supposed to reflect. But it would have the advantage of showing a "fuller" bar, hinting at used capacity.)

The label should contain the list of flavors, or something to that effect.

Very rough mockup (sorry):

```
hana_c24_m365
hana_c48_m729
hana_c96_m1458                        [ #################################### ]
hana_c144_m2188
hana_c192_m2917

hana_c24_m729
hana_c48_m1459
hana_c96_m2918                        [ ##################                   ]
hana_c144_m4377
hana_c192_m5835
```

Note, referring to the list of flavors in the mockup: Nova's `GET /flavors/` will mention the _complete_ first block, the _complete_ second block, _none_, or _all_ of them. You'll probably don't care, since you can just dynamically identify-and-group them by NUMA-trait required, but I thought I'd mention it.

cc @dhoeller @joker-at-work

(I'm off, as you might be aware, but I'm still on Github, so if there's any feedback/questions, just ping me here.)

**Comment by andypf** [comment]
@grandchild 
"(But only if available in that region, i.e. Nova's GET /flavors/ must mention them.)"
Can we use https://docs.openstack.org/api-ref/placement/?expanded=list-resource-providers-detail#list-resource-providers with param "required= CUSTOM_NUMASIZE_C48_M729, CUSTOM_NUMASIZE_C48_M1459"?

**Comment by joker-at-work** [comment]
> Results will be filtered to include only resource providers having all the specified traits

No. A resource-provider would only have one of those traits. NUMA node size defines how many CPUs belong to how much RAM. Can't be different for the same hardware.

This means, you would need to make 2 requests to acquire that information.

**Comment by andypf** [comment]
Done! #925
