### ISSUE TITLE
BGP VPN implementation 

### ISSUE THREAD

**Issue by velp** [sapcc/elektra#930]
BGP VPN feature is now available for the end-users. We have to add a new TAB for "Networks & Routers" section in the dashboard. This TAB must:
1. show list of available bgpvpns for project (API ref: https://docs.openstack.org/api-ref/network/v2/index.html#list-bgp-vpns)
2. provide controls to manage router associations (API ref: https://docs.openstack.org/api-ref/network/v2/index.html#create-router-association)

### Functionality
The end-user should be able to:
1. see the list of available bgpvpns in project
2. create/update/delete router associations for available bgpvpns

### Columns for the list BGPVPN table:
- `Name` - field `name` from the response
- `Associated Routers` - field `routers` from the response
- `Owning Project` - field `project_id` from the response
- `Shared` - field `shared` from the response

### Columns for the details page:

Tab `Overview`:
- `ID` - field `id` from the response
- `Name` - field `name` from the response
- `Routers` - field `routers` from the response
- `Project` - field `project_id` from the response
- `Shared` - field `shared` from the response
- `Type` - field `type` from the response
- `Import Targets` - field `import_targets` from the repsonse
- `Export Targets` - field `export_targets` from the response

Tab `Routers` (table of associated routers) columns:
- `Name / ID` - name and id of associated router
- `Networks` - IDs and subnets of private networks on the router

Also, this Tab should contain controls to add/delete router associations.

**Comment by andypf** [comment]
implemented!
