### ISSUE TITLE
SecurityGroup: add columns Owning project and Shared

### ISSUE THREAD

**Issue by velp** [sapcc/elektra#935]
Since we are now showing shared security groups in the general list of groups (https://github.com/sapcc/elektra/issues/929), it would be nice to show also the Owner project and the shared flag for each group in the list. We have to add two columns to the list of Security Groups:
`Owning Project` - the source project, field `tenant_id` from API response body
`Shared` - field `shared` from API response body, can be true/false and means that SG was shared.

Example how it looks like in Networks list:
![Screen Shot 2021-09-09 at 10 49 51](https://user-images.githubusercontent.com/8326634/132645355-e0569114-bdf3-4b15-b8ce-0c8bb1707ba0.png)

**Comment by andypf** [comment]
done with 957c598118bf5e200dc57847a55858957204d27b
