### ISSUE TITLE
Manila: add support for scheduler_hints.

### ISSUE THREAD

**Issue by galkindmitrii** [sapcc/elektra#941]
Manila allows users to specify **scheduler_hints** when creating a new share.
Scheduler hints might supply one or multiple share uuid-s under either **different_host** or **same_host** clause.

This feature needs to be optional when a user creates a new share from the dashboard.

An example API call:

curl -vvv -X POST https://share-3.qa-de-1.cloud.sap/v2/PROJECT_ID/shares -H "X-Auth-Token: $TOKEN" -H "X-Openstack-Manila-Api-Version: 2.51" -H "User-Agent: python-manilaclient" -H "Accept: application/json" -H "Content-Type: application/json" -d '{"share": {"size": 1, "snapshot_id": null, "name": "different_from_my_share", "description": null, "metadata": {}, "share_proto": "NFS", "share_network_id": "a84c7f5a-715d-4d68-bbdb-71c53de90d24", "share_type": null, "is_public": false, "availability_zone": null, "scheduler_hints": {"different_host": ["a94dd637-12de-438c-8a89-6c13485ed268", "7427b4b6-03b7-47d4-aa06-a58298e0cae2"] }}}'

**Comment by hgw77** [comment]
This issue has been closed due to over a year of inactivity. If this matter is still relevant, please feel free to reopen it by adding a comment.
