### ISSUE TITLE
lbaasv2: display operating_state ERROR as Offline

### ISSUE THREAD

**Issue by notandy** [sapcc/elektra#944]
I hesitated to date to diverge from the upstream notation of operating_state (https://docs.openstack.org/api-ref/load-balancer/v2/#operating-status-codes), but it seems customers still always confused about the ERROR state and think that it's a problem on our Infrastructure side. 

Since Elektra is opinionated, let's do something opinionated towards the customer. I suggest to display the ERROR `operating_state` of all objects as OFFLINE.

**Comment by ArtieReus** [comment]
I got confused also at the beginning. From my point of view this is a good idea. Lets do it.
