### ISSUE TITLE
Customer cannot identify shared security groups in the server creation dialog.

### ISSUE THREAD

**Issue by velp** [sapcc/elektra#946]
Because we started providing a shared security group, our customer can have two (and more) SGs with the same names. For example, a customer has one security group with the name `test-sg-rbac` in his project, and another one is shared from the second project. In CLI this situation looks like:

```
$ openstack security group list | grep test-sg-rbac
| 0127648d-e01a-43b6-9960-f706195860a2 | test-sg-rbac                        | test-sg-rbac                        | e9141fb24eee4b3e9f25ae69cda31132 | []       |
| b5c53c61-8bc5-43e3-9832-3d019f1cd004 | test-sg-rbac                        |                                     | 7243f3f80a99434292d6766069d3961a | []       |
```

but in the dashboard it is impossible to understand where is what, he see two names:
![Screen Shot 2021-09-28 at 16 06 36](https://user-images.githubusercontent.com/8326634/135092780-07e5f527-a322-412d-971c-5ce3b3c9dfb5.png)

We have to:
1. add information about the owner (project_id or project_name) for shared SGs in the list
2. use security group ID instead of name for server creation request to the Nova API

**Comment by andypf** [comment]
Fixed with 0782284565c6c26ee80cfbfb9835793c6971f046
